In [ ]:
!pip install pymupdf

In [ ]:
!pip install pytesseract

In [1]:
import re

def clean_text(text):
    # remove page markers like --- Page 1 ---
    text = re.sub(r"--- Page \d+ ---", "", text)
    
    # remove standalone page numbers (lines with only numbers)
    text = re.sub(r"^\s*\d+\s*$", "", text, flags=re.MULTILINE)
    
    # remove OCR garbage like .१10.80४.110
    text = re.sub(r"\.\d*[०-९\d./]+", "", text)
    
    # remove multiple newlines
    text = re.sub(r"\n{2,}", "\n", text)
    
    # remove extra spaces
    text = re.sub(r"\s{2,}", " ", text)
    
    return text.strip()

In [1]:
from pdf2image import convert_from_path
import pytesseract
import os

# -----------------------------
# 1. Setup paths
# -----------------------------

# Path to Tesseract OCR executable
pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

# Path to Poppler bin folder
poppler_path = r"C:\Program Files\poppler-25.12.0\Library\bin"

In [ ]:

# PDF file path
pdf_path = r"Data\budget_speech_2081.pdf"

# Output text file
output_text_file = r"budget_speech_text.txt"


# 2. Convert PDF to images

try:
    images = convert_from_path(pdf_path, dpi=300, poppler_path=poppler_path)
    print(f"Number of pages found: {len(images)}")
except Exception as e:
    print("Error converting PDF to images:", e)
    exit()


# 3. Extract text from images

def extract_text_from_images(images):
    extracted_text = []
    for i, page in enumerate(images):
        text = pytesseract.image_to_string(page, lang="nep")
        text = clean_text(text)
        extracted_text.append({
            "page_number": i,
            "text": text
        })
    return extracted_text

text_data = extract_text_from_images(images)

# -----------------------------
# 4. Save text to file
# -----------------------------
with open(output_text_file, "w", encoding="utf-8") as f:
    for page in text_data:
        f.write(f"--- Page {page['page_number']} ---\n")
        f.write(page['text'])
        f.write("\n\n")

print(f"Extraction completed! Text saved to {output_text_file}")


# 5. Optional: print first page text

if text_data:
    print("\nFirst page preview:\n")
    print(text_data[0]["text"])

Directly Import the saved data from txt data

In [2]:
import re

with open('Data/budget_speech_text.txt', 'r', encoding='utf-8') as f:
    content = f.read()

text_data = []
pattern = r'--- Page (\d+) ---\s*(.*?)(?=--- Page \d+ ---|$)'
matches = re.findall(pattern, content, re.DOTALL)

for page_num, page_text in matches:
    text_data.append({
        "page_number": int(page_num),
        "text": clean_text(page_text)
    })

# Check result
print(f"Total pages: {len(text_data)}")
print(text_data[0])   # First page
print(text_data[-1])  # Last page

Total pages: 110
{'page_number': 1, 'text': 'प्रतिनिधि सभाका सम्माननीय सभामुख महोदय,\nराष्ट्रिय सभाका सम्माननीय अध्यक्ष महोदय,\n१.\nनेपाल सरकारको अर्थमन्त्रीको हैसियतले आर्थिक वर्ष २०८१/८२ को\nबजेट प्रस्तुत गर्न यस सम्मानित सदनमा उपस्थित भएको छु। सर्वप्रथम\nसत्रौं गणतन्त्र दिवसको अवसरमा सम्पूर्ण नेपाली दिदीबहिनी तथा\nदाजुभाइमा हार्दिक शुभकामना व्यक्त गर्दछु।\nनेपालका प्रथम शहीद लखन थापा, २००७ सालको परिवर्तन, २०४६\nसालको आन्दोलन, २०५२ सालको जनयुद्ध, २०६२/६३ को\nजनआन्दोलन, मधेश आन्दोलन, आदिबासी जनजाति आन्दोलन लगायतका\nसम्पूर्ण लोकतान्त्रिक आन्दोलनका महान शहीदहरूप्रति हार्दिक\nश्रद्धाञ्जली अर्पण गर्दछु । बेपत्ता परिवार, घाइते, अपाङ्गता भएका व्यक्ति\nलगायत सबै जनसमुदायप्रति उच्च सम्मान प्रकट गर्दछु।\nकेही समयदेखि शिथिल रहेको मुलुकको अर्थतन्त्र सरकारको निरन्तर\nप्रयासबाट चलायमान हुँदै गएको छ। विगतमा शुरू गरिएका आर्थिक\nसुधारका उपलब्धिलाई संस्थागत गर्दै बदलिँदो विश्व अर्थव्यवस्था र\nनेपालको वस्तुगत आवश्यकतालाई दृष्टिगत गरी अर्थतन्त्रलाई सबल र\nउत्थानशील बनाउन आवश्यक ठानेको छु। संविधानको परिकल्पना\nअनुसार राष्ट्रिय अर्थतन्त्रलाई आत्मनिर्भर, स्वतन्त्र तथा उन्नतिशील\nबनाउँदै समाजवाद उन्मुख समृद्ध राष्ट्र निर्माणका लागि नयाँ चरणको\nआर्थिक सुधार आवश्यक देखिएको छ ।\nबजेटलाई आर्थिक तथा सामाजिक क्षेत्रमा देखिएका चुनौती सम्बोधन गर्दै\nआम नागरिकमा आत्मविश्वास र आशा जगाउने दस्तावेजको रूपमा\nप्रस्तुत गरेको छु। समृद्ध नेपाल, सुखी नेपालीको राष्ट्रिय आकांक्षा पूरा\nगर्न र आर्थिक सुधारका कार्यक्रम अगाडि बढाउन आगामी आर्थिक\nवर्षलाई आर्थिक सुधारको वर्ष घोषणा गरेको छु।'}
{'page_number': 110, 'text': "आर्थिक वर्ष आर्थिक वर्ष\n'उपक्षेत्रगत कार्यक्रम २०८०/८१ सम्मको | २०८१/८२ को\nअनुमान अन्त्यमा हुने\nब्ला। पप\nप्रधानमन्त्री रोजगार कार्यक्रममार्फत रोजगारी _\nसंख्या (हजार) ६० ६०\nसिर्जना (वार्षिक)\nसामाजिक सुरक्षा कोषमा आवद्ध हुने श्रमिकको\n_ संख्या (हजार) १५०० २५००\nसंख्या\nसामाजिक सुरक्षा कोषमा सूचीकृत\nरोजगारदाताको सं संख्या (हजार)\nरोजगारदाताको संख्या\nश्रम तथा\nमता व्यवसायिक तथा सीप विकास तालिम लिनेको\n_ संख्या (हजार)\nसंख्या (प्रतिवर्ष)\nसामाजिक\nसुरक्षा\nप्रतिष्ठान निरीक्षण (श्रम कानूनको परिपालना,\n0514 समेत)\nबालश्रम निरीक्षण (प्रतिवर्ष) प्रतिष्ठान संख्या\nश्रम अडिट प्रतिष्ठान संख्या\nस्थानीय तहको\nसंख्या\n२३ युवा यु\n२४ अर्थ साना किसान विकास लघु वित्त संस्थामा गरेको हजार\n4० | लगानीबाट रोजगारी सिर्जना वि\nप्रतिष्ठान संख्या\nबालमुक्त स्थानीय तह घोषणा"}

In [3]:
text_data[0]

{'page_number': 1,
 'text': 'प्रतिनिधि सभाका सम्माननीय सभामुख महोदय,\nराष्ट्रिय सभाका सम्माननीय अध्यक्ष महोदय,\n१.\nनेपाल सरकारको अर्थमन्त्रीको हैसियतले आर्थिक वर्ष २०८१/८२ को\nबजेट प्रस्तुत गर्न यस सम्मानित सदनमा उपस्थित भएको छु। सर्वप्रथम\nसत्रौं गणतन्त्र दिवसको अवसरमा सम्पूर्ण नेपाली दिदीबहिनी तथा\nदाजुभाइमा हार्दिक शुभकामना व्यक्त गर्दछु।\nनेपालका प्रथम शहीद लखन थापा, २००७ सालको परिवर्तन, २०४६\nसालको आन्दोलन, २०५२ सालको जनयुद्ध, २०६२/६३ को\nजनआन्दोलन, मधेश आन्दोलन, आदिबासी जनजाति आन्दोलन लगायतका\nसम्पूर्ण लोकतान्त्रिक आन्दोलनका महान शहीदहरूप्रति हार्दिक\nश्रद्धाञ्जली अर्पण गर्दछु । बेपत्ता परिवार, घाइते, अपाङ्गता भएका व्यक्ति\nलगायत सबै जनसमुदायप्रति उच्च सम्मान प्रकट गर्दछु।\nकेही समयदेखि शिथिल रहेको मुलुकको अर्थतन्त्र सरकारको निरन्तर\nप्रयासबाट चलायमान हुँदै गएको छ। विगतमा शुरू गरिएका आर्थिक\nसुधारका उपलब्धिलाई संस्थागत गर्दै बदलिँदो विश्व अर्थव्यवस्था र\nनेपालको वस्तुगत आवश्यकतालाई दृष्टिगत गरी अर्थतन्त्रलाई सबल र\nउत्थानशील बनाउन आवश्यक ठानेको छु। संविधानको परिकल्पना\nअनुसार राष्ट्रिय अर्थतन्त्रलाई आत्मनिर्भर, स्वतन्त्र तथा उन्नतिशील\nबनाउँदै समाजवाद उन्मुख समृद्ध राष्ट्र निर्माणका लागि नयाँ चरणको\nआर्थिक सुधार आवश्यक देखिएको छ ।\nबजेटलाई आर्थिक तथा सामाजिक क्षेत्रमा देखिएका चुनौती सम्बोधन गर्दै\nआम नागरिकमा आत्मविश्वास र आशा जगाउने दस्तावेजको रूपमा\nप्रस्तुत गरेको छु। समृद्ध नेपाल, सुखी नेपालीको राष्ट्रिय आकांक्षा पूरा\nगर्न र आर्थिक सुधारका कार्यक्रम अगाडि बढाउन आगामी आर्थिक\nवर्षलाई आर्थिक सुधारको वर्ष घोषणा गरेको छु।'}

In [4]:
text_data[1]

{'page_number': 2,
 'text': '५. तेस्रो लगानी सम्मेलन उत्साहपूर्ण रूपमा सम्पन्न भएको छ। सम्मेलनमा\nप्रमुख राजनीतिक दलबाट लगानीमैत्री वातावरण निर्माण गर्न र निजी\nक्षेत्रको आत्मबल बढाउन सामुहिक प्रतिबद्धता व्यक्त भएको छ।\nलगानीसम्बन्धी आठ कानूनमा एकैपटक गरिएको सुधारले सरकारको\nलगानीमैत्री वातावरण निर्माण गर्ने प्रतिबद्धताको पुनर्पुष्टि भएको छ।\n६. सुशासन, सामाजिक न्याय र समृद्धिको सोच सहितको सोह्रौं योजना\nनेपाल सरकारले स्वीकृत गरेको छ। नागरिकको जीवनमा अनुभूतयोग्य\nपरिवर्तन हासिल गर्ने योजनाको उद्देश्य पूरा गर्न सघाउ पुग्ने गरी बजेट\nतर्जुमा गरेको छु।\n७. बजेट तर्जुमा गर्दा नेपालको संविधान, पन्ध्रां योजनाको समीक्षा, सोह्रौं\nयोजनाको सोँच, गणतन्त्रका डेढ दशकको उपलब्धिको सर्मीक्षा,\nसम्मानित सदनमा पेश गरिएको विनियोजन विधेयकका सिद्धान्त र\nप्राथमिकता तथा त्यसमाथि माननीय सदस्यहरूबाट प्राप्त सुझाव एवं\nनेपाल सरकारको नीति तथा कार्यक्रमलाई प्रमुख आधार बनाएको छु।\nसंसदका विषयगत समिति, प्रदेश तथा स्थानीय तह, राजनीतिक दल,\nसंघ-संस्था, विद्वृत वर्ग, निजी क्षेत्र, विकास साझेदार एवं सञ्चार क्षेत्र\nलगायत आम नागरिकबाट प्राप्त सल्लाह सुझाव समेतलाई प्राथमिकतामा\nराखेको छु।\nसम्माननीय महोदय,\n८. मुलुकमा संघीय लोकतान्त्रिक गणतन्त्र घोषणा भएको आज सोह्र वर्ष\nपूरा भएको छ। यस अवधिमा आर्थिक तथा सामाजिक क्षेत्रमा हासिल\nभएका मुख्य उपलब्धि प्रस्तुत गर्ने अनुमति चाहन्छु।'}

Now lets make the text more cleaner

In [8]:
import pandas as pd
pd = pd.DataFrame(text_data)

In [9]:
pd.head()

   page_number                                               text
0            0  संघीय संसदको संयुक्त बेठकमा २०८१ साल जेठ १५ गत...
1            1  प्रतिनिधि सभाका सम्माननीय सभामुख महोदय,\nराष्ट...
2            2  ५. तेस्रो लगानी सम्मेलन उत्साहपूर्ण रूपमा सम्प...
3            3  १०.\n११.\nआर्थिक वर्ष २०६४/६५ मा रु खर्ब १५ अर...
4            4  १३.\n१४.\nप्रतिहजार ६१ बाट ३३ मा र मातृ मृत्यु...

In [11]:
import random
random.sample(text_data,k=1)

[{'page_number': 2,
  'text': '५. तेस्रो लगानी सम्मेलन उत्साहपूर्ण रूपमा सम्पन्न भएको छ। सम्मेलनमा\nप्रमुख राजनीतिक दलबाट लगानीमैत्री वातावरण निर्माण गर्न र निजी\nक्षेत्रको आत्मबल बढाउन सामुहिक प्रतिबद्धता व्यक्त भएको छ।\nलगानीसम्बन्धी आठ कानूनमा एकैपटक गरिएको सुधारले सरकारको\nलगानीमैत्री वातावरण निर्माण गर्ने प्रतिबद्धताको पुनर्पुष्टि भएको छ।\n६. सुशासन, सामाजिक न्याय र समृद्धिको सोच सहितको सोह्रौं योजना\nनेपाल सरकारले स्वीकृत गरेको छ। नागरिकको जीवनमा अनुभूतयोग्य\nपरिवर्तन हासिल गर्ने योजनाको उद्देश्य पूरा गर्न सघाउ पुग्ने गरी बजेट\nतर्जुमा गरेको छु।\n७. बजेट तर्जुमा गर्दा नेपालको संविधान, पन्ध्रां योजनाको समीक्षा, सोह्रौं\nयोजनाको सोँच, गणतन्त्रका डेढ दशकको उपलब्धिको सर्मीक्षा,\nसम्मानित सदनमा पेश गरिएको विनियोजन विधेयकका सिद्धान्त र\nप्राथमिकता तथा त्यसमाथि माननीय सदस्यहरूबाट प्राप्त सुझाव एवं\nनेपाल सरकारको नीति तथा कार्यक्रमलाई प्रमुख आधार बनाएको छु।\nसंसदका विषयगत समिति, प्रदेश तथा स्थानीय तह, राजनीतिक दल,\nसंघ-संस्था, विद्वृत वर्ग, निजी क्षेत्र, विकास साझेदार एवं सञ्चार क्षेत्र\nलगायत आम नागरिकबाट प्राप्त सल्लाह सुझाव समेतलाई प्राथमिकतामा\nराखेको छु।\nसम्माननीय महोदय,\n८. मुलुकमा संघीय लोकतान्त्रिक गणतन्त्र घोषणा भएको आज सोह्र वर्ष\nपूरा भएको छ। यस अवधिमा आर्थिक तथा सामाजिक क्षेत्रमा हासिल\nभएका मुख्य उपलब्धि प्रस्तुत गर्ने अनुमति चाहन्छु।'}]

Lets preprocess further.So split the sentences using Spacy,like split the each sentences in pages.

In [ ]:
# import spacy

# nlp = spacy.blank("ne")
# nlp.add_pipe("sentencizer")

# #for demo
# text = "मलाई नेपाली भाषा मन पर्छ। यो धेरै सुन्दर भाषा हो। म काठमाडौंमा बस्छु।"

# doc = nlp(text)

# for sent in doc.sents:
#     print(sent.text)

Lets use the spacy for our text dataset

In [ ]:
# for items in text_data:
#     doc = nlp(items["text"])
#     items["Sentence"] = [str(sentence).strip() for sentence in doc.sents]
#     items["Sentence_count"] = len(items["Sentence"])

# text_data[3]

Spacy ley hamro data ma jaha jaha ru xa tya ni split garyo so yesley context bigaryo then lets split manually

In [5]:
import re

#define splitter  func
def split_nepali_sentences(text):
    abbreviations = ['रु', 'डा', 'श्री', 'नं', 'क्र', 'पृ']
    text = text.replace('\n', ' ')
    for abbr in abbreviations:
        text = text.replace(abbr + '.', abbr + '###')
    
    sentences = re.split(r'(?<=[।॥!?])\s+', text)
    sentences = [s.replace('###', '.') for s in sentences]
    sentences = [s.strip() for s in sentences 
                 if s.strip() and not re.fullmatch(r'[०-९]+\.', s.strip())]
    return sentences

In [ ]:
# #delete the spacy splitter
# for items in text_data:
#     del items["Sentence"]
#     del items["Sentence_count"]

In [6]:
text_data[0]

{'page_number': 1,
 'text': 'प्रतिनिधि सभाका सम्माननीय सभामुख महोदय,\nराष्ट्रिय सभाका सम्माननीय अध्यक्ष महोदय,\n१.\nनेपाल सरकारको अर्थमन्त्रीको हैसियतले आर्थिक वर्ष २०८१/८२ को\nबजेट प्रस्तुत गर्न यस सम्मानित सदनमा उपस्थित भएको छु। सर्वप्रथम\nसत्रौं गणतन्त्र दिवसको अवसरमा सम्पूर्ण नेपाली दिदीबहिनी तथा\nदाजुभाइमा हार्दिक शुभकामना व्यक्त गर्दछु।\nनेपालका प्रथम शहीद लखन थापा, २००७ सालको परिवर्तन, २०४६\nसालको आन्दोलन, २०५२ सालको जनयुद्ध, २०६२/६३ को\nजनआन्दोलन, मधेश आन्दोलन, आदिबासी जनजाति आन्दोलन लगायतका\nसम्पूर्ण लोकतान्त्रिक आन्दोलनका महान शहीदहरूप्रति हार्दिक\nश्रद्धाञ्जली अर्पण गर्दछु । बेपत्ता परिवार, घाइते, अपाङ्गता भएका व्यक्ति\nलगायत सबै जनसमुदायप्रति उच्च सम्मान प्रकट गर्दछु।\nकेही समयदेखि शिथिल रहेको मुलुकको अर्थतन्त्र सरकारको निरन्तर\nप्रयासबाट चलायमान हुँदै गएको छ। विगतमा शुरू गरिएका आर्थिक\nसुधारका उपलब्धिलाई संस्थागत गर्दै बदलिँदो विश्व अर्थव्यवस्था र\nनेपालको वस्तुगत आवश्यकतालाई दृष्टिगत गरी अर्थतन्त्रलाई सबल र\nउत्थानशील बनाउन आवश्यक ठानेको छु। संविधानको परिकल्पना\nअनुसार राष्ट्रिय अर्थतन्त्रलाई आत्मनिर्भर, स्वतन्त्र तथा उन्नतिशील\nबनाउँदै समाजवाद उन्मुख समृद्ध राष्ट्र निर्माणका लागि नयाँ चरणको\nआर्थिक सुधार आवश्यक देखिएको छ ।\nबजेटलाई आर्थिक तथा सामाजिक क्षेत्रमा देखिएका चुनौती सम्बोधन गर्दै\nआम नागरिकमा आत्मविश्वास र आशा जगाउने दस्तावेजको रूपमा\nप्रस्तुत गरेको छु। समृद्ध नेपाल, सुखी नेपालीको राष्ट्रिय आकांक्षा पूरा\nगर्न र आर्थिक सुधारका कार्यक्रम अगाडि बढाउन आगामी आर्थिक\nवर्षलाई आर्थिक सुधारको वर्ष घोषणा गरेको छु।'}

In [7]:
for items in text_data:
    items["Sentence"] = split_nepali_sentences(items["text"])
    items["Sentence_Count"] = len(items["Sentence"])

In [8]:
text_data[0]

{'page_number': 1,
 'text': 'प्रतिनिधि सभाका सम्माननीय सभामुख महोदय,\nराष्ट्रिय सभाका सम्माननीय अध्यक्ष महोदय,\n१.\nनेपाल सरकारको अर्थमन्त्रीको हैसियतले आर्थिक वर्ष २०८१/८२ को\nबजेट प्रस्तुत गर्न यस सम्मानित सदनमा उपस्थित भएको छु। सर्वप्रथम\nसत्रौं गणतन्त्र दिवसको अवसरमा सम्पूर्ण नेपाली दिदीबहिनी तथा\nदाजुभाइमा हार्दिक शुभकामना व्यक्त गर्दछु।\nनेपालका प्रथम शहीद लखन थापा, २००७ सालको परिवर्तन, २०४६\nसालको आन्दोलन, २०५२ सालको जनयुद्ध, २०६२/६३ को\nजनआन्दोलन, मधेश आन्दोलन, आदिबासी जनजाति आन्दोलन लगायतका\nसम्पूर्ण लोकतान्त्रिक आन्दोलनका महान शहीदहरूप्रति हार्दिक\nश्रद्धाञ्जली अर्पण गर्दछु । बेपत्ता परिवार, घाइते, अपाङ्गता भएका व्यक्ति\nलगायत सबै जनसमुदायप्रति उच्च सम्मान प्रकट गर्दछु।\nकेही समयदेखि शिथिल रहेको मुलुकको अर्थतन्त्र सरकारको निरन्तर\nप्रयासबाट चलायमान हुँदै गएको छ। विगतमा शुरू गरिएका आर्थिक\nसुधारका उपलब्धिलाई संस्थागत गर्दै बदलिँदो विश्व अर्थव्यवस्था र\nनेपालको वस्तुगत आवश्यकतालाई दृष्टिगत गरी अर्थतन्त्रलाई सबल र\nउत्थानशील बनाउन आवश्यक ठानेको छु। संविधानको परिकल्पना\nअनुसार राष्ट्रिय अर्थतन्त्रलाई आत्मनिर्भर, स्वतन्त्र तथा उन्नतिशील\nबनाउँदै समाजवाद उन्मुख समृद्ध राष्ट्र निर्माणका लागि नयाँ चरणको\nआर्थिक सुधार आवश्यक देखिएको छ ।\nबजेटलाई आर्थिक तथा सामाजिक क्षेत्रमा देखिएका चुनौती सम्बोधन गर्दै\nआम नागरिकमा आत्मविश्वास र आशा जगाउने दस्तावेजको रूपमा\nप्रस्तुत गरेको छु। समृद्ध नेपाल, सुखी नेपालीको राष्ट्रिय आकांक्षा पूरा\nगर्न र आर्थिक सुधारका कार्यक्रम अगाडि बढाउन आगामी आर्थिक\nवर्षलाई आर्थिक सुधारको वर्ष घोषणा गरेको छु।',
 'Sentence': ['प्रतिनिधि सभाका सम्माननीय सभामुख महोदय, राष्ट्रिय सभाका सम्माननीय अध्यक्ष महोदय, १. नेपाल सरकारको अर्थमन्त्रीको हैसियतले आर्थिक वर्ष २०८१/८२ को बजेट प्रस्तुत गर्न यस सम्मानित सदनमा उपस्थित भएको छु।',
  'सर्वप्रथम सत्रौं गणतन्त्र दिवसको अवसरमा सम्पूर्ण नेपाली दिदीबहिनी तथा दाजुभाइमा हार्दिक शुभकामना व्यक्त गर्दछु।',
  'नेपालका प्रथम शहीद लखन थापा, २००७ सालको परिवर्तन, २०४६ सालको आन्दोलन, २०५२ सालको जनयुद्ध, २०६२/६३ को जनआन्दोलन, मधेश आन्दोलन, आदिबासी जनजाति आन्दोलन लगायतका सम्पूर्ण लोकतान्त्रिक आन्दोलनका महान शहीदहरूप्रति हार्दिक श्रद्धाञ्जली अर्पण गर्दछु ।',
  'बेपत्ता परिवार, घाइते, अपाङ्गता भएका व्यक्ति लगायत सबै जनसमुदायप्रति उच्च सम्मान प्रकट गर्दछु।',
  'केही समयदेखि शिथिल रहेको मुलुकको अर्थतन्त्र सरकारको निरन्तर प्रयासबाट चलायमान हुँदै गएको छ।',
  'विगतमा शुरू गरिएका आर्थिक सुधारका उपलब्धिलाई संस्थागत गर्दै बदलिँदो विश्व अर्थव्यवस्था र नेपालको वस्तुगत आवश्यकतालाई दृष्टिगत गरी अर्थतन्त्रलाई सबल र उत्थानशील बनाउन आवश्यक ठानेको छु।',
  'संविधानको परिकल्पना अनुसार राष्ट्रिय अर्थतन्त्रलाई आत्मनिर्भर, स्वतन्त्र तथा उन्नतिशील बनाउँदै समाजवाद उन्मुख समृद्ध राष्ट्र निर्माणका लागि नयाँ चरणको आर्थिक सुधार आवश्यक देखिएको छ ।',
  'बजेटलाई आर्थिक तथा सामाजिक क्षेत्रमा देखिएका चुनौती सम्बोधन गर्दै आम नागरिकमा आत्मविश्वास र आशा जगाउने दस्तावेजको रूपमा प्रस्तुत गरेको छु।',
  'समृद्ध नेपाल, सुखी नेपालीको राष्ट्रिय आकांक्षा पूरा गर्न र आर्थिक सुधारका कार्यक्रम अगाडि बढाउन आगामी आर्थिक वर्षलाई आर्थिक सुधारको वर्ष घोषणा गरेको छु।'],
 'Sentence_Count': 9}

In [9]:
text_data[1]

{'page_number': 2,
 'text': '५. तेस्रो लगानी सम्मेलन उत्साहपूर्ण रूपमा सम्पन्न भएको छ। सम्मेलनमा\nप्रमुख राजनीतिक दलबाट लगानीमैत्री वातावरण निर्माण गर्न र निजी\nक्षेत्रको आत्मबल बढाउन सामुहिक प्रतिबद्धता व्यक्त भएको छ।\nलगानीसम्बन्धी आठ कानूनमा एकैपटक गरिएको सुधारले सरकारको\nलगानीमैत्री वातावरण निर्माण गर्ने प्रतिबद्धताको पुनर्पुष्टि भएको छ।\n६. सुशासन, सामाजिक न्याय र समृद्धिको सोच सहितको सोह्रौं योजना\nनेपाल सरकारले स्वीकृत गरेको छ। नागरिकको जीवनमा अनुभूतयोग्य\nपरिवर्तन हासिल गर्ने योजनाको उद्देश्य पूरा गर्न सघाउ पुग्ने गरी बजेट\nतर्जुमा गरेको छु।\n७. बजेट तर्जुमा गर्दा नेपालको संविधान, पन्ध्रां योजनाको समीक्षा, सोह्रौं\nयोजनाको सोँच, गणतन्त्रका डेढ दशकको उपलब्धिको सर्मीक्षा,\nसम्मानित सदनमा पेश गरिएको विनियोजन विधेयकका सिद्धान्त र\nप्राथमिकता तथा त्यसमाथि माननीय सदस्यहरूबाट प्राप्त सुझाव एवं\nनेपाल सरकारको नीति तथा कार्यक्रमलाई प्रमुख आधार बनाएको छु।\nसंसदका विषयगत समिति, प्रदेश तथा स्थानीय तह, राजनीतिक दल,\nसंघ-संस्था, विद्वृत वर्ग, निजी क्षेत्र, विकास साझेदार एवं सञ्चार क्षेत्र\nलगायत आम नागरिकबाट प्राप्त सल्लाह सुझाव समेतलाई प्राथमिकतामा\nराखेको छु।\nसम्माननीय महोदय,\n८. मुलुकमा संघीय लोकतान्त्रिक गणतन्त्र घोषणा भएको आज सोह्र वर्ष\nपूरा भएको छ। यस अवधिमा आर्थिक तथा सामाजिक क्षेत्रमा हासिल\nभएका मुख्य उपलब्धि प्रस्तुत गर्ने अनुमति चाहन्छु।',
 'Sentence': ['५. तेस्रो लगानी सम्मेलन उत्साहपूर्ण रूपमा सम्पन्न भएको छ।',
  'सम्मेलनमा प्रमुख राजनीतिक दलबाट लगानीमैत्री वातावरण निर्माण गर्न र निजी क्षेत्रको आत्मबल बढाउन सामुहिक प्रतिबद्धता व्यक्त भएको छ।',
  'लगानीसम्बन्धी आठ कानूनमा एकैपटक गरिएको सुधारले सरकारको लगानीमैत्री वातावरण निर्माण गर्ने प्रतिबद्धताको पुनर्पुष्टि भएको छ।',
  '६. सुशासन, सामाजिक न्याय र समृद्धिको सोच सहितको सोह्रौं योजना नेपाल सरकारले स्वीकृत गरेको छ।',
  'नागरिकको जीवनमा अनुभूतयोग्य परिवर्तन हासिल गर्ने योजनाको उद्देश्य पूरा गर्न सघाउ पुग्ने गरी बजेट तर्जुमा गरेको छु।',
  '७. बजेट तर्जुमा गर्दा नेपालको संविधान, पन्ध्रां योजनाको समीक्षा, सोह्रौं योजनाको सोँच, गणतन्त्रका डेढ दशकको उपलब्धिको सर्मीक्षा, सम्मानित सदनमा पेश गरिएको विनियोजन विधेयकका सिद्धान्त र प्राथमिकता तथा त्यसमाथि माननीय सदस्यहरूबाट प्राप्त सुझाव एवं नेपाल सरकारको नीति तथा कार्यक्रमलाई प्रमुख आधार बनाएको छु।',
  'संसदका विषयगत समिति, प्रदेश तथा स्थानीय तह, राजनीतिक दल, संघ-संस्था, विद्वृत वर्ग, निजी क्षेत्र, विकास साझेदार एवं सञ्चार क्षेत्र लगायत आम नागरिकबाट प्राप्त सल्लाह सुझाव समेतलाई प्राथमिकतामा राखेको छु।',
  'सम्माननीय महोदय, ८. मुलुकमा संघीय लोकतान्त्रिक गणतन्त्र घोषणा भएको आज सोह्र वर्ष पूरा भएको छ।',
  'यस अवधिमा आर्थिक तथा सामाजिक क्षेत्रमा हासिल भएका मुख्य उपलब्धि प्रस्तुत गर्ने अनुमति चाहन्छु।'],
 'Sentence_Count': 9}

Lets remove the first Page jun hamlai chahhina so

Remove the unwnated words

In [10]:
REMOVE_KEYWORDS = [
    "सम्माननीय",
    "सभामुख",
    "अध्यक्ष",
    "शुभकामना",
    "श्रद्धाञ्जली",
    "शहीद",
    "उपस्थित भएको छु"
]

def is_clean_sentence(sentence):
    for word in REMOVE_KEYWORDS:
        if word in sentence:
            return False
    return True


cleaned_text_data = []

for item in text_data:
    cleaned_sentences = []
    
    for s in item["Sentence"]:
        if is_clean_sentence(s):
            cleaned_sentences.append(s)
    
    cleaned_text_data.append({
        "Page_number": item["page_number"],
        "Text": item["text"],
        "Sentences": cleaned_sentences
    })


print(cleaned_text_data[0])

{'Page_number': 1, 'Text': 'प्रतिनिधि सभाका सम्माननीय सभामुख महोदय,\nराष्ट्रिय सभाका सम्माननीय अध्यक्ष महोदय,\n१.\nनेपाल सरकारको अर्थमन्त्रीको हैसियतले आर्थिक वर्ष २०८१/८२ को\nबजेट प्रस्तुत गर्न यस सम्मानित सदनमा उपस्थित भएको छु। सर्वप्रथम\nसत्रौं गणतन्त्र दिवसको अवसरमा सम्पूर्ण नेपाली दिदीबहिनी तथा\nदाजुभाइमा हार्दिक शुभकामना व्यक्त गर्दछु।\nनेपालका प्रथम शहीद लखन थापा, २००७ सालको परिवर्तन, २०४६\nसालको आन्दोलन, २०५२ सालको जनयुद्ध, २०६२/६३ को\nजनआन्दोलन, मधेश आन्दोलन, आदिबासी जनजाति आन्दोलन लगायतका\nसम्पूर्ण लोकतान्त्रिक आन्दोलनका महान शहीदहरूप्रति हार्दिक\nश्रद्धाञ्जली अर्पण गर्दछु । बेपत्ता परिवार, घाइते, अपाङ्गता भएका व्यक्ति\nलगायत सबै जनसमुदायप्रति उच्च सम्मान प्रकट गर्दछु।\nकेही समयदेखि शिथिल रहेको मुलुकको अर्थतन्त्र सरकारको निरन्तर\nप्रयासबाट चलायमान हुँदै गएको छ। विगतमा शुरू गरिएका आर्थिक\nसुधारका उपलब्धिलाई संस्थागत गर्दै बदलिँदो विश्व अर्थव्यवस्था र\nनेपालको वस्तुगत आवश्यकतालाई दृष्टिगत गरी अर्थतन्त्रलाई सबल र\nउत्थानशील बनाउन आवश्यक ठानेको छु। संविधानको परिकल्पना\nअनुसार राष्ट्रिय अर्थतन्त्रलाई आत्मनिर्भर, स्वतन्त्र तथा उन्नतिशील\nबनाउँदै समाजवाद उन्मुख समृद्ध राष्ट्र निर्माणका लागि नयाँ चरणको\nआर्थिक सुधार आवश्यक देखिएको छ ।\nबजेटलाई आर्थिक तथा सामाजिक क्षेत्रमा देखिएका चुनौती सम्बोधन गर्दै\nआम नागरिकमा आत्मविश्वास र आशा जगाउने दस्तावेजको रूपमा\nप्रस्तुत गरेको छु। समृद्ध नेपाल, सुखी नेपालीको राष्ट्रिय आकांक्षा पूरा\nगर्न र आर्थिक सुधारका कार्यक्रम अगाडि बढाउन आगामी आर्थिक\nवर्षलाई आर्थिक सुधारको वर्ष घोषणा गरेको छु।', 'Sentences': ['बेपत्ता परिवार, घाइते, अपाङ्गता भएका व्यक्ति लगायत सबै जनसमुदायप्रति उच्च सम्मान प्रकट गर्दछु।', 'केही समयदेखि शिथिल रहेको मुलुकको अर्थतन्त्र सरकारको निरन्तर प्रयासबाट चलायमान हुँदै गएको छ।', 'विगतमा शुरू गरिएका आर्थिक सुधारका उपलब्धिलाई संस्थागत गर्दै बदलिँदो विश्व अर्थव्यवस्था र नेपालको वस्तुगत आवश्यकतालाई दृष्टिगत गरी अर्थतन्त्रलाई सबल र उत्थानशील बनाउन आवश्यक ठानेको छु।', 'संविधानको परिकल्पना अनुसार राष्ट्रिय अर्थतन्त्रलाई आत्मनिर्भर, स्वतन्त्र तथा उन्नतिशील बनाउँदै समाजवाद उन्मुख समृद्ध राष्ट्र निर्माणका लागि नयाँ चरणको आर्थिक सुधार आवश्यक देखिएको छ ।', 'बजेटलाई आर्थिक तथा सामाजिक क्षेत्रमा देखिएका चुनौती सम्बोधन गर्दै आम नागरिकमा आत्मविश्वास र आशा जगाउने दस्तावेजको रूपमा प्रस्तुत गरेको छु।', 'समृद्ध नेपाल, सुखी नेपालीको राष्ट्रिय आकांक्षा पूरा गर्न र आर्थिक सुधारका कार्यक्रम अगाडि बढाउन आगामी आर्थिक वर्षलाई आर्थिक सुधारको वर्ष घोषणा गरेको छु।']}

Now lets add the Metadata tagging and also add the topics for the each sentence

In [11]:
keyword_map = {
    "शिक्षा": ["विद्यालय", "शिक्षा", "विद्यार्थी", "पाठ्यक्रम", "शिक्षण"],
    
    "स्वास्थ्य": ["स्वास्थ्य", "चिकित्सा", "उपचार", "डाक्टर", "अस्पताल", "औषधि"],
    
    "अर्थतन्त्र": [
        "अर्थतन्त्र", "अर्थव्यवस्था", "आर्थिक", "बजेट","राजस्व", "आय", "वित्त", "लगानी", "सुधार"
         ],
    
    "कृषि": ["कृषि", "खेती", "बाली", "उत्पादन", "किसान"],
    
    "पूर्वाधार": ["सडक", "पूर्वाधार", "पुल", "सञ्चार", "पानी", "विद्युत"],
    
    "विज्ञान तथा प्रविधि": ["विज्ञान", "प्रविधि", "आईटी", "डिजिटल", "अनुसन्धान"],
    
    "उद्योग र व्यापार": ["उद्योग", "व्यापार", "उद्यम", "कारखाना", "नौकरी"],
    
    "पर्यटन": ["पर्यटन", "यात्रा", "टुरिज्म"],
    
    "सामाजिक सुरक्षा": ["पेंशन", "सामाजिक सुरक्षा", "अनुदान", "भत्ता"]
}

In [22]:
def keyword_matching(sentence, topic, keyword_map):
    """Count how many keywords from a specific topic appear in the sentence"""
    score = 0
    if topic in keyword_map:
        for keyword in keyword_map[topic]:
            if keyword in sentence:
                score += 1
    return score

In [13]:
#embedding model ma pathauney vanda aagadi hamley list lai string ma lanuparxa so
topic_sentences = {topic:" ".join(keywords) for topic, keywords in keyword_map.items()}

In [14]:

from sentence_transformers import SentenceTransformer

model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

c:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 998.51it/s]
BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [15]:
topic_embeddings = model.encode(list(topic_sentences.values()))

In [21]:
from sklearn.metrics.pairwise import cosine_similarity

# Store the list of topics to use for indexing
topics_list = list(keyword_map.keys())

#for embedding score
def embedding_score(sentence, topic, topics_list, topic_embeddings):
    """Get similarity score for a specific topic"""
    sentence_embedding = model.encode([sentence])
    topic_index = topics_list.index(topic)
    similarity = cosine_similarity(sentence_embedding, [topic_embeddings[topic_index]])[0][0]
    return similarity

In [23]:
#combine the scores 
def hybrid_score(sentence, topic, keyword_map, topics_list, topic_embeddings):
    """Calculate combined keyword and embedding score for a specific topic"""
    keyword_scores = keyword_matching(sentence, topic, keyword_map)
    embedding_scores = embedding_score(sentence, topic, topics_list, topic_embeddings)
    # Normalize keyword scores to 0-1 range
    max_keywords = max(len(keywords) for keywords in keyword_map.values())
    normalized_keyword = (keyword_scores / max_keywords) if max_keywords > 0 else 0
    combined_score = 0.7 * normalized_keyword + 0.3 * embedding_scores
    return combined_score

In [24]:
#Now return the topic with highest score for each sentence
def classify_sentence(sentence, keyword_map, topics_list, topic_embeddings):
    """Classify sentence to the topic with highest score"""
    scores = {}
    # Calculate score for each topic
    for topic in keyword_map.keys():
        scores[topic] = hybrid_score(sentence, topic, keyword_map, topics_list, topic_embeddings)
    
    best_topic = max(scores, key=scores.get)
    best_score = scores[best_topic]
    
    if best_score < 0.1:  # threshold for classification
        return "अन्य", best_score
    
    return best_topic, best_score

In [25]:
add_metadata_text = []

for item in cleaned_text_data:
    page = item["Page_number"]
    sentence = item["Sentences"]

   

    #add metadata to each sentence
    for i,s in enumerate(sentence):
         #get the topic and score
        topic,scores = classify_sentence(s, keyword_map, topics_list, topic_embeddings)
        add_metadata_text.append(
            {
                "text": s,
                "metadata":{
                    "page":page,
                    "sentence_id":f"p{page}_s{i+1}",
                    "language": "ne",
                    "source": "Budget Report 2081",
                    "topics": topic,
                    "scores": round(scores, 3)
                }
            }
        )

In [30]:
add_metadata_text[1]

{'text': 'केही समयदेखि शिथिल रहेको मुलुकको अर्थतन्त्र सरकारको निरन्तर प्रयासबाट चलायमान हुँदै गएको छ।',
 'metadata': {'page': 1,
  'sentence_id': 'p1_s2',
  'language': 'ne',
  'source': 'Budget Report 2081',
  'topics': 'अर्थतन्त्र',
  'scores': np.float32(0.181)}}

In [31]:
from collections import Counter

def count_topics(data):
    topics = []

    for chunk in data:
        topic = chunk["metadata"].get("topics", "other")  # Fixed: use "topics" not "topic"
        topics.append(topic)

    return Counter(topics)


counts = count_topics(add_metadata_text)

print(counts)

Counter({'अर्थतन्त्र': 320, 'अन्य': 116, 'पूर्वाधार': 100, 'विज्ञान तथा प्रविधि': 84, 'स्वास्थ्य': 79, 'कृषि': 62, 'शिक्षा': 55, 'उद्योग र व्यापार': 38, 'सामाजिक सुरक्षा': 23, 'पर्यटन': 23})

In [32]:
add_metadata_text[:10]

[{'text': 'बेपत्ता परिवार, घाइते, अपाङ्गता भएका व्यक्ति लगायत सबै जनसमुदायप्रति उच्च सम्मान प्रकट गर्दछु।',
  'metadata': {'page': 1,
   'sentence_id': 'p1_s1',
   'language': 'ne',
   'source': 'Budget Report 2081',
   'topics': 'स्वास्थ्य',
   'scores': np.float32(0.101)}},
 {'text': 'केही समयदेखि शिथिल रहेको मुलुकको अर्थतन्त्र सरकारको निरन्तर प्रयासबाट चलायमान हुँदै गएको छ।',
  'metadata': {'page': 1,
   'sentence_id': 'p1_s2',
   'language': 'ne',
   'source': 'Budget Report 2081',
   'topics': 'अर्थतन्त्र',
   'scores': np.float32(0.181)}},
 {'text': 'विगतमा शुरू गरिएका आर्थिक सुधारका उपलब्धिलाई संस्थागत गर्दै बदलिँदो विश्व अर्थव्यवस्था र नेपालको वस्तुगत आवश्यकतालाई दृष्टिगत गरी अर्थतन्त्रलाई सबल र उत्थानशील बनाउन आवश्यक ठानेको छु।',
  'metadata': {'page': 1,
   'sentence_id': 'p1_s3',
   'language': 'ne',
   'source': 'Budget Report 2081',
   'topics': 'अर्थतन्त्र',
   'scores': np.float32(0.453)}},
 {'text': 'संविधानको परिकल्पना अनुसार राष्ट्रिय अर्थतन्त्रलाई आत्मनिर्भर, स्वतन्त्र तथा उन्नतिशील बनाउँदै समाजवाद उन्मुख समृद्ध राष्ट्र निर्माणका लागि नयाँ चरणको आर्थिक सुधार आवश्यक देखिएको छ ।',
  'metadata': {'page': 1,
   'sentence_id': 'p1_s4',
   'language': 'ne',
   'source': 'Budget Report 2081',
   'topics': 'अर्थतन्त्र',
   'scores': np.float32(0.276)}},
 {'text': 'बजेटलाई आर्थिक तथा सामाजिक क्षेत्रमा देखिएका चुनौती सम्बोधन गर्दै आम नागरिकमा आत्मविश्वास र आशा जगाउने दस्तावेजको रूपमा प्रस्तुत गरेको छु।',
  'metadata': {'page': 1,
   'sentence_id': 'p1_s5',
   'language': 'ne',
   'source': 'Budget Report 2081',
   'topics': 'अर्थतन्त्र',
   'scores': np.float32(0.276)}},
 {'text': 'समृद्ध नेपाल, सुखी नेपालीको राष्ट्रिय आकांक्षा पूरा गर्न र आर्थिक सुधारका कार्यक्रम अगाडि बढाउन आगामी आर्थिक वर्षलाई आर्थिक सुधारको वर्ष घोषणा गरेको छु।',
  'metadata': {'page': 1,
   'sentence_id': 'p1_s6',
   'language': 'ne',
   'source': 'Budget Report 2081',
   'topics': 'अर्थतन्त्र',
   'scores': np.float32(0.31)}},
 {'text': '५. तेस्रो लगानी सम्मेलन उत्साहपूर्ण रूपमा सम्पन्न भएको छ।',
  'metadata': {'page': 2,
   'sentence_id': 'p2_s1',
   'language': 'ne',
   'source': 'Budget Report 2081',
   'topics': 'अर्थतन्त्र',
   'scores': np.float32(0.16)}},
 {'text': 'सम्मेलनमा प्रमुख राजनीतिक दलबाट लगानीमैत्री वातावरण निर्माण गर्न र निजी क्षेत्रको आत्मबल बढाउन सामुहिक प्रतिबद्धता व्यक्त भएको छ।',
  'metadata': {'page': 2,
   'sentence_id': 'p2_s2',
   'language': 'ne',
   'source': 'Budget Report 2081',
   'topics': 'अर्थतन्त्र',
   'scores': np.float32(0.195)}},
 {'text': 'लगानीसम्बन्धी आठ कानूनमा एकैपटक गरिएको सुधारले सरकारको लगानीमैत्री वातावरण निर्माण गर्ने प्रतिबद्धताको पुनर्पुष्टि भएको छ।',
  'metadata': {'page': 2,
   'sentence_id': 'p2_s3',
   'language': 'ne',
   'source': 'Budget Report 2081',
   'topics': 'अर्थतन्त्र',
   'scores': np.float32(0.297)}},
 {'text': '६. सुशासन, सामाजिक न्याय र समृद्धिको सोच सहितको सोह्रौं योजना नेपाल सरकारले स्वीकृत गरेको छ।',
  'metadata': {'page': 2,
   'sentence_id': 'p2_s4',
   'language': 'ne',
   'source': 'Budget Report 2081',
   'topics': 'अर्थतन्त्र',
   'scores': np.float32(0.14)}}]

In [85]:
import json
from collections import defaultdict


MIN_SCORE       = 0.20
MIN_TEXT_LEN    = 15
GARBAGE_TOKENS  = {"0 0", "0?", "॥०॥", "0० 0", "०?", "0 0 0"}


def clean_metadata(records: list) -> list:
    cleaned = []

    for record in records:
        text  = record.get("text", "").strip()
        meta  = record.get("metadata", {})
        score = float(meta.get("scores", 0))
        topics = meta.get("topics", [])

        # normalize topics → always a list
        if isinstance(topics, str):
            topics = [topics] if topics else []

        # filters
        if score < MIN_SCORE:                              continue
        if len(text) < MIN_TEXT_LEN:                       continue
        if any(g in text for g in GARBAGE_TOKENS):         continue

        cleaned.append({
            "text": text,
            "metadata": {
                "page":        meta.get("page"),
                "sentence_id": meta.get("sentence_id"),
                "language":    meta.get("language", "ne"),
                "source":      meta.get("source"),
                "topics":      topics,
                "scores":      round(score, 4),
                "fiscal_year": "2081",
            }
        })

    return cleaned

In [86]:
cleaned_data = clean_metadata(add_metadata_text)

In [90]:
with open("cleaned_budget_2081.json", "w", encoding="utf-8") as f:
    json.dump(cleaned_data, f, ensure_ascii=False, indent=2)

print(" Saved to cleaned_budget_2081.json")

 Saved to cleaned_budget_2081.json

In [89]:
print(f"Total sentences: {len(cleaned_data)}")

Total sentences: 318

At first group the similar sentence topic wise then its easy to chunking

In [91]:
#सबै sentences लाई उनीहरूको topic अनुसार छुट्याएर groups बनाउँछ
from collections import defaultdict

def group_by_topic(data):
    topic_map = defaultdict(list)

    for item in data:
        topics = item["metadata"].get("topics",[])

        #if there are no topics
        if len(topics) == 0:
            topic = "other"
        else:
            topic = topics[0]  #Primary topics

        topic_map[topic].append(item)

    return topic_map

In [92]:
topic_map = group_by_topic(cleaned_data)

In [93]:
print(topic_map)

defaultdict(<class 'list'>, {'अर्थतन्त्र': [{'text': 'विगतमा शुरू गरिएका आर्थिक सुधारका उपलब्धिलाई संस्थागत गर्दै बदलिँदो विश्व अर्थव्यवस्था र नेपालको वस्तुगत आवश्यकतालाई दृष्टिगत गरी अर्थतन्त्रलाई सबल र उत्थानशील बनाउन आवश्यक ठानेको छु।', 'metadata': {'page': 1, 'sentence_id': 'p1_s3', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.453, 'fiscal_year': '2081'}}, {'text': 'संविधानको परिकल्पना अनुसार राष्ट्रिय अर्थतन्त्रलाई आत्मनिर्भर, स्वतन्त्र तथा उन्नतिशील बनाउँदै समाजवाद उन्मुख समृद्ध राष्ट्र निर्माणका लागि नयाँ चरणको आर्थिक सुधार आवश्यक देखिएको छ ।', 'metadata': {'page': 1, 'sentence_id': 'p1_s4', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.276, 'fiscal_year': '2081'}}, {'text': 'बजेटलाई आर्थिक तथा सामाजिक क्षेत्रमा देखिएका चुनौती सम्बोधन गर्दै आम नागरिकमा आत्मविश्वास र आशा जगाउने दस्तावेजको रूपमा प्रस्तुत गरेको छु।', 'metadata': {'page': 1, 'sentence_id': 'p1_s5', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.276, 'fiscal_year': '2081'}}, {'text': 'समृद्ध नेपाल, सुखी नेपालीको राष्ट्रिय आकांक्षा पूरा गर्न र आर्थिक सुधारका कार्यक्रम अगाडि बढाउन आगामी आर्थिक वर्षलाई आर्थिक सुधारको वर्ष घोषणा गरेको छु।', 'metadata': {'page': 1, 'sentence_id': 'p1_s6', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.31, 'fiscal_year': '2081'}}, {'text': 'लगानीसम्बन्धी आठ कानूनमा एकैपटक गरिएको सुधारले सरकारको लगानीमैत्री वातावरण निर्माण गर्ने प्रतिबद्धताको पुनर्पुष्टि भएको छ।', 'metadata': {'page': 2, 'sentence_id': 'p2_s3', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.297, 'fiscal_year': '2081'}}, {'text': 'नागरिकको जीवनमा अनुभूतयोग्य परिवर्तन हासिल गर्ने योजनाको उद्देश्य पूरा गर्न सघाउ पुग्ने गरी बजेट तर्जुमा गरेको छु।', 'metadata': {'page': 2, 'sentence_id': 'p2_s5', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.22, 'fiscal_year': '2081'}}, {'text': '७. बजेट तर्जुमा गर्दा नेपालको संविधान, पन्ध्रां योजनाको समीक्षा, सोह्रौं योजनाको सोँच, गणतन्त्रका डेढ दशकको उपलब्धिको सर्मीक्षा, सम्मानित सदनमा पेश गरिएको विनियोजन विधेयकका सिद्धान्त र प्राथमिकता तथा त्यसमाथि माननीय सदस्यहरूबाट प्राप्त सुझाव एवं नेपाल सरकारको नीति तथा कार्यक्रमलाई प्रमुख आधार बनाएको छु।', 'metadata': {'page': 2, 'sentence_id': 'p2_s6', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.211, 'fiscal_year': '2081'}}, {'text': '१०. ११. आर्थिक वर्ष २०६४/६५ मा रु खर्ब १५ अर्ब रहेको कुल गार्हस्थ्य उत्पादन चालु आर्थिक वर्ष रु. ५७ खर्ब ५ अर्ब हुने अनुमान छ।', 'metadata': {'page': 3, 'sentence_id': 'p3_s1', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.257, 'fiscal_year': '2081'}}, {'text': 'प्रति व्यक्ति राष्ट्रिय आय अमेरिकी डलर ४ सय ९१ बाट बढेर १ हजार ४ सय ५६ पुगेको छ।', 'metadata': {'page': 3, 'sentence_id': 'p3_s2', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.265, 'fiscal_year': '2081'}}, {'text': 'गुणस्तरीय पूर्वाधारको कमी, दक्ष जनशक्तिको न्यूनता तथा उत्पादन, उत्पादकत्व र रोजगारीमा अपेक्षित वृद्धि हुन नसकेका कारण आर्थिक वृद्धिको दर न्यून हुनपुग्यो।', 'metadata': {'page': 4, 'sentence_id': 'p4_s11', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.213, 'fiscal_year': '2081'}}, {'text': '१५. १६. १७. १८. अर्थतन्त्रमा लामो समयदेखि संरचनात्मक चुनौती रहेकोमा पछिल्लो समय सार्वजनिक र निजी लगानी खुम्चिएको, सार्वजनिक वित्तमा असन्तुलन बढ्दै गएको, सार्वजनिक क्रण व्यवस्थापन खर्च बढ्दै गएको र पुँजीगत खर्च गर्ने क्षमता घट्दै गएको कारण थप चुनौती सिर्जना भएको छ।', 'metadata': {'page': 5, 'sentence_id': 'p5_s1', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.428, 'fiscal_year': '2081'}}, {'text': 'वर्षौदेखि उस्तै प्रकृतिका समस्या तथा चुनौती दोहोरिईरहेकाले अर्थतन्त्र र विकास व्यवस्थापनमा देखिएको क्षमता अभावको दुष्चक्र तोड्दै सुधारका नयाँ कार्यक्रम मार्फत समृद्धिको लक्ष्य हासिल गर्नुपर्ने देखिएको छ।', 'metadata': {'page': 5, 'sentence_id': 'p5_s2', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.308, 'fiscal_year': '2081'}}, {'text': 'सूचना प्रविधिमा आएको क्रान्ति, कृत्रिम बौद्धिकताको बढ्दो प्रयोग र ज्ञानमा आधारित अर्थतन्त्रको विकास भइरहेको सन्दर्भमा नेपालको अर्थतन्त्रले नयाँ पुस्ता अनुकूलको आर्थिक सुधारको माग गरेको छ।', 'metadata': {'page': 5, 'sentence_id': 'p5_s3', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.335, 'fiscal_year': '2081'}}, {'text': 'सन्\u200c २०२६ मा विकासोन्मुख राष्ट्रमा स्तरोन्नति भए पश्चात लिनुपर्ने रणनीति, सन्\u200c २०३० भित्र दिगो विकास लक्ष्य हासिल गर्ने अन्तर्राष्ट्रिय प्रतिबद्धता र मध्यम आय भएको राष्ट्रको स्तरमा पुग्ने राष्ट्रिय लक्ष्यलाई दृष्टिगत गरी आगामी आर्थिक वर्षमा आर्थिक सुधारलाई तीव्रता दिइनेछ ।', 'metadata': {'page': 5, 'sentence_id': 'p5_s5', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.404, 'fiscal_year': '2081'}}, {'text': '११. ७) ७) उपभोक्ता मागमा कमी आउनु, कर्जाको विस्तार न्यून हुनु, उत्पादनमूलक क्षेत्र न्यून क्षमतामा सञ्चालन हुनु र वस्तुको आयातमा कमी आउनु लगायतका कारण आर्थिक क्रियाकलापमा अपेक्षित विस्तार हुन नसकेकाले चालु आर्थिक वर्षमा आर्थिक वृद्धिदर उत्पादकको मूल्यमा ३ प्रतिशत मात्र हुने प्रारम्भिक अनुमान छ।', 'metadata': {'page': 6, 'sentence_id': 'p6_s1', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.343, 'fiscal_year': '2081'}}, {'text': 'चालु आर्थिक वर्षको चैत महिनामा औसत मूल्य वृद्धि ४ प्रतिशतमा सीमित रहेको छ।', 'metadata': {'page': 6, 'sentence_id': 'p6_s2', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.228, 'fiscal_year': '2081'}}, {'text': 'चालु आर्थिक वर्षको चैत मसान्तसम्म आयात २ प्रतिशतले र निर्यात ३ प्रतिशतले घटेको छ।', 'metadata': {'page': 6, 'sentence_id': 'p6_s3', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.221, 'fiscal_year': '2081'}}, {'text': 'शोधनान्तर स्थिति रु. ३ खर्ब ६५ अर्बले बचतमा रहेको छ।', 'metadata': {'page': 6, 'sentence_id': 'p6_s4', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.216, 'fiscal_year': '2081'}}, {'text': 'विदेशी मुद्राको सञ्चिति १२ महिनाको वस्तु र सेवा आयात धान्न पर्याप्त रहेको छ।', 'metadata': {'page': 6, 'sentence_id': 'p6_s5', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.209, 'fiscal_year': '2081'}}, {'text': 'आर्थिक वर्ष २०८०%८१ मा कुल सरकारी खर्च रु. १५ खर्ब ३० अर्ब ३५ करोड अर्थात विनियोजनको ८७ प्रतिशत हुने संशोधित अनुमान छ।', 'metadata': {'page': 6, 'sentence_id': 'p6_s7', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.29, 'fiscal_year': '2081'}}, {'text': 'कुल सरकारी खर्च मध्ये चालु खर्च रु. १० खर्ब ६७ अर्ब ४९ करोड अर्थात विनियोजनको ९३ प्रतिशत, पुँजीगत खर्च रु. २ खर्ब १५ अर्ब ३० करोड अर्थात विनियोजनको ७१ प्रतिशत र बित्तीय व्यवस्थातर्फ रु. २ खर्ब ४७ अर्ब ५५ करोड अर्थात विनियोजनको ८० प्रतिशत खर्च हुने संशोधित अनुमान छ।', 'metadata': {'page': 6, 'sentence_id': 'p6_s8', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.213, 'fiscal_year': '2081'}}, {'text': 'चालु आर्थिक वर्ष राजस्व संकलन रु. १२ खर्ब ५३ अर्ब ५२ करोड संशोधित हुने अनुमान छ यो लक्ष्यको तुलनामा ८८ प्रतिशत हो।', 'metadata': {'page': 6, 'sentence_id': 'p6_s9', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.359, 'fiscal_year': '2081'}}, {'text': 'चालु आर्थिक वर्षको लागि खर्च व्यहोर्ने स्रोतमध्ये आन्तरिक क्रणबाट रु. २ खर्ब ४० अर्ब व्यहोरिने अनुमान रहेकोमा वैशाख मसान्तसम्म रु. १ खर्ब ९१ अर्ब उठाइएको छ।', 'metadata': {'page': 6, 'sentence_id': 'p6_s11', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.306, 'fiscal_year': '2081'}}, {'text': '२४. चालु आर्थिक वर्षको मन्त्रालय र निकायगत बजेट विनियोजन र खर्चको प्रगति विवरण, मुलुकको प्रमुख आर्थिक-सामाजिक परिसूचक र तथ्याङ्क समावेश भएको आर्थिक सर्वेक्षण र सार्वजनिक संस्थानको प्रगति समेटिएको विवरण सम्मानित सदन समक्ष पेश गरिसकेको छु।', 'metadata': {'page': 7, 'sentence_id': 'p7_s1', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.338, 'fiscal_year': '2081'}}, {'text': 'बजेटका पाँच उद्देश्य देहायबमोजिम रहेका छन्\u200cः (1) उत्पादन, उत्पादकत्व र रोजगारी वृद्धि गर्नु, (2) निजी क्षेत्रको मनोबल बढाउँदै लगानी वृद्धि गर्नु र आर्थिक क्रियाकलापमा तीव्रता ल्याउनु, (३) मानव संसाधन विकास गर्नु, (4) स्रोत र साधनलाई सन्तुलित र समन्यायिक ढङ्गले परिचालन गरी आर्थिक असमानता र गरिबी न्यूनीकरण गर्नु, र (5) सार्वजनिक सेवा प्रवाहलाई प्रभावकारी बनाउनु ।', 'metadata': {'page': 7, 'sentence_id': 'p7_s2', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.439, 'fiscal_year': '2081'}}, {'text': 'बजेटका पाँच प्राथमिकता देहायबमोजिम तय गरेको छुः (1) आर्थिक सुधार र निजी क्षेत्रको प्रवर्दन, (2) कृषि, उर्जा, सूचना प्रविधि, पर्यटन, औद्योगिक विकास तथा पूर्वाधार निर्माण, (३) शिक्षा, स्वास्थ्य लगायत सामाजिक क्षेत्रको विकास, (4) समावेशिता र सामाजिक सुरक्षा, र', 'metadata': {'page': 7, 'sentence_id': 'p7_s3', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.393, 'fiscal_year': '2081'}}, {'text': '(5) सुशासन प्रवर्द्धन तथा सार्वजनिक सेवा प्रवाहमा सुधार ।', 'metadata': {'page': 8, 'sentence_id': 'p8_s1', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.208, 'fiscal_year': '2081'}}, {'text': 'अब म आर्थिक सुधारका पाँच रणनीति प्रस्तुत गर्दछुः (क) (ग) संरचनागत सुधार राष्ट्रिय अर्थतन्त्रको सम्भाव्यता विश्लेषणको आधारमा आर्थिक वृद्धिका प्रमुख सम्वाहक क्षेत्र पहिचान गरी उच्च दरको आर्थिक वृद्धि हासिल गर्न र एकीकृत आर्थिक कोरिडोर विकास, डिजिटल अर्थतन्त्रको विस्तार र हरित अर्थतन्त्रको आधार निर्माण गर्न नयाँ चरणको आर्थिक सुधार कार्यक्रम अघि बढाइनेछ।', 'metadata': {'page': 8, 'sentence_id': 'p8_s2', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.407, 'fiscal_year': '2081'}}, {'text': 'यस सम्बन्धमा सिफारिश गर्न एक उच्चस्तरीय आर्थिक सुधार सुझाव आयोग गठन गरिनेछ ।', 'metadata': {'page': 8, 'sentence_id': 'p8_s3', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.325, 'fiscal_year': '2081'}}, {'text': 'व्यावसायिक वातावरण सुधार उद्योग र लगानी सम्बन्धी कानून परिमार्जन, नीतिगत स्थायित्व एवं लगानी सुरक्षाको प्रत्याभूति, कन्द्री रेटिङ, द्विपक्षीय लगानी र दोहोरो करमुक्ति सम्झौता, प्रविधि हस्तान्तरण वापत विदेशमा लैजान पाउने सेवा शुल्कको सीमा वृद्धि, विदेशमा प्रविधि हस्तान्तरण गरी आर्जित आयलाई निश्चित सीमासम्म पुन:विदेशमा लगानी गर्न पाउने व्यवस्था र स-सानो पुँजी संकलन गरी उद्यम तथा पूर्वाधार विकासमा लगानी गर्ने कम्पनी स्थापना गर्न निजी क्षेत्रलाई प्रोत्साहित गरी व्यावसायिक वातावरणमा सुधार गरिनेछ।', 'metadata': {'page': 8, 'sentence_id': 'p8_s4', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.399, 'fiscal_year': '2081'}}, {'text': 'सार्वजनिक वित्त प्रणाली सुधार कर प्रणालीमा सुधार एवं नीतिगत स्थायित्व, वित्तीय र मौद्रिक नीतिबीचको तादात्म्यता, सार्वजनिक क्रणको दिगोपना, वित्तीय क्षेत्रको स्थायित्व र पुँजी परिचालन अभिवृद्धि, मितव्ययी र प्रतिफलमुखी सार्वजनिक खर्च व्यवस्थापन र उद्देश्यमूलक वित्तीय हस्तान्तरण सुनिश्चित हुने गरी सार्वजनिक वित्त प्रणालीमा सुधार गरिनेछ ।', 'metadata': {'page': 8, 'sentence_id': 'p8_s5', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.344, 'fiscal_year': '2081'}}, {'text': '(घ) वित्तीय क्षेत्र सुधार दोस्रो वित्तीय क्षेत्र विकास रणनीति तर्जुमा एवं कार्यान्वयन, डिजिटल भुक्तानीको प्रवर्द्धन, केन्द्रीय बैंक डिजिटल करेन्सी तयारी, औपचारिक क्षेत्रमा आर्थिक गतिविधिको विस्तार, हरित वित्त लगायतका नवीनतम्\u200c वित्तीय उपकरणको उपयोग गर्ने गरी वित्तीय क्षेत्र सुधारका कार्यक्रम अगाडि बढाइनेछ।', 'metadata': {'page': 9, 'sentence_id': 'p9_s1', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.4, 'fiscal_year': '2081'}}, {'text': 'बजेटका पाँच रूपान्तरणकारी क्षेत्र देहायबमोजिम रहेका छन्\u200c: (क) कृषि क्षेत्र रूपान्तरण, (ख) उर्जा क्षेत्र विकास, (ग) सूचना प्रविधि विकास, (घ) पर्यटन प्रवर्दन, र (ङ) उद्यमशीलता र औद्योगिक विकास ।', 'metadata': {'page': 9, 'sentence_id': 'p9_s4', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.229, 'fiscal_year': '2081'}}, {'text': '२६, राष्ट्रिय प्राकृतिक स्रोत तथा वित्त आयोगको सिफारिशका आधारमा वित्तीय समानीकरण अनुदान प्रदेशको लागि रु. ६० अर्ब र स्थानीय तहको लागि रु. ८८ अर्ब हस्तान्तरण गर्ने व्यवस्था मिलाएको छु।', 'metadata': {'page': 9, 'sentence_id': 'p9_s5', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.347, 'fiscal_year': '2081'}}, {'text': '२८. प्रदेश र स्थानीय तहलाई पूर्वाधारका आयोजना कार्यान्वयन गर्न समपूरक अनुदान क्रमशः रु. ६ अर्ब २० करोड र रु. ७ अर्ब विनियोजन गरेको छु।', 'metadata': {'page': 10, 'sentence_id': 'p10_s2', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.23, 'fiscal_year': '2081'}}, {'text': '२९, प्रदेश र स्थानीय तहमा राजस्व बाँडफाँटबाट रु. १ खर्ब १९ अर्ब हस्तान्तरण हुने अनुमान छ।', 'metadata': {'page': 10, 'sentence_id': 'p10_s5', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.286, 'fiscal_year': '2081'}}, {'text': '३०. राजस्व बाँडफाँट र अनुदान गरी प्रदेश र स्थानीय तहमा आगामी आर्थिक वर्ष रु. १ खर्ब ६७ अर्ब हस्तान्तरण हुने अनुमान छ।', 'metadata': {'page': 10, 'sentence_id': 'p10_s6', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.361, 'fiscal_year': '2081'}}, {'text': 'सरकारी, निजी, सहकारी तथा विकास साझेदारबाट कृषि क्षेत्रमा लगानी अभिवृद्धि गर्न विक्रम सम्वत्\u200c २०८१ देखि२०९१ सम्मको अवधिलाई कृषिमा लगानी दशक घोषणा गरिएको छ।', 'metadata': {'page': 10, 'sentence_id': 'p10_s8', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.266, 'fiscal_year': '2081'}}, {'text': 'स्वदेशमा नै बढी उत्पादन क्षमता भएका दुधालु पशु उत्पादन गर्न गाई र भैसीमा नश्ल सुधारका लागि रु करोड विनियोजन गरेको छु।', 'metadata': {'page': 13, 'sentence_id': 'p13_s6', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.234, 'fiscal_year': '2081'}}, {'text': 'उर्जा क्षेत्र विकास «१. आगामी आर्थिक वर्ष ९ सय मेगावाट विद्युत थप गरी राष्ट्रिय प्रणालीको विद्युत क्षमता ४ हजार ५ सय मेगावाट पुच्याइनेछ।', 'metadata': {'page': 14, 'sentence_id': 'p14_s6', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.217, 'fiscal_year': '2081'}}, {'text': 'वैदेशिक रोजगारीमा गएका व्यक्तिको लगानीमा ७७ मेगावाटको घुन्सा र ७० मेगावाटको सिम्बुवा जलविद्युत आयोजना निर्माण कार्य अगाडि बढाइनेछ।', 'metadata': {'page': 14, 'sentence_id': 'p14_s12', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.254, 'fiscal_year': '2081'}}, {'text': '२२. ५ ४. २२, ५६, जनताको जलविद्युत कार्यक्रम अन्तर्गत १ हजार ६३ मेगावाटको माथिल्लो अरुण, १ सय ६ मेगावाटको जगदुल्ला, १ सय मेगावाटको तामाकोशी पाँचौं, ४२ मेगावाटको मोदी ए र २ सय १० मेगावाटको चैनपुर-सेती जलविद्युत आयोजनाको निर्माण कार्य शुरू गरिनेछ।', 'metadata': {'page': 15, 'sentence_id': 'p15_s1', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.204, 'fiscal_year': '2081'}}, {'text': 'हरित हाइड्रोजन प्रवर्धन गर्न अनुसन्धान र विकासका लागि आवश्यक बजेट व्यवस्था गरेको छु।', 'metadata': {'page': 15, 'sentence_id': 'p15_s6', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.235, 'fiscal_year': '2081'}}, {'text': 'यस आयोजनाको लागि रु. ५९ करोड विनियोजन गरेको छु।', 'metadata': {'page': 16, 'sentence_id': 'p16_s12', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.239, 'fiscal_year': '2081'}}, {'text': 'बुद्ध परिपथ, शिव परिपथ, रामायण परिपथ, किराँत सांस्कृतिक परिपथको मार्ग निर्धारण गरी पर्यटन प्रवर्द्धन गर्न बजेट व्यवस्था गरेको छु।', 'metadata': {'page': 18, 'sentence_id': 'p18_s5', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.212, 'fiscal_year': '2081'}}, {'text': 'निजगढ अन्तर्राष्ट्रिय विमानस्थल सार्वजनिक-निजी साझेदारीमा निर्माण गर्न आगामी आर्थिक वर्ष भित्र लगानीको ढाँचा र पूर्व तयारी कार्य सम्पन्न गरिनेछ।', 'metadata': {'page': 19, 'sentence_id': 'p19_s8', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.213, 'fiscal_year': '2081'}}, {'text': 'उद्चयमशीलता र औद्योगिक विकास ७८. ७९, ८०. आन्तरिक उत्पादन बढाई आयात प्रतिस्थापन र निर्यात वृद्धि गर्न तथा उत्पादनलाई रोजगारीसँग आवद्ध गराउन उत्पादन र रोजगारीका लागि साझेदारी कार्यक्रम सञ्चालन गरिनेछ।', 'metadata': {'page': 20, 'sentence_id': 'p20_s3', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.213, 'fiscal_year': '2081'}}, {'text': '८१. ८३. ८४. ८१. निजी क्षेत्रसँगको सहकार्यमा प्रदेशलाई विशिष्टिकृत आर्थिक केन्द्रको रूपमा विकास गरिनेछ।', 'metadata': {'page': 21, 'sentence_id': 'p21_s1', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.201, 'fiscal_year': '2081'}}, {'text': 'बिभिन्न सम्झौतित कोषको रकम प्राइभेट इक्विटी फण्ड र भेञ्चर क्यापिटल फण्डका धितोपत्र एकाइमा लगानी गर्ने व्यवस्था मिलाइनेछ।', 'metadata': {'page': 23, 'sentence_id': 'p23_s2', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.249, 'fiscal_year': '2081'}}, {'text': 'उद्योग र लगानीसँग सम्बन्धित कानूनमा परिमार्जन गरिनेछ।', 'metadata': {'page': 23, 'sentence_id': 'p23_s7', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.21, 'fiscal_year': '2081'}}, {'text': 'वन ऐन र जग्गाप्राप्ति ऐनलाई समयानुकूल बनाई लगानी सहजीकरण गरिनेछ।', 'metadata': {'page': 23, 'sentence_id': 'p23_s10', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.225, 'fiscal_year': '2081'}}, {'text': '२. तराई-मधेशका सीमान्तकृत तथा पिछडिएको क्षेत्रको आर्थिक-सामाजिक विकास र सशक्तीकरणका लागि तराई-मधेश समृद्धि कार्यक्रम कार्यान्वयन गर्न रु. १ अर्ब छुट्याएको छु।', 'metadata': {'page': 25, 'sentence_id': 'p25_s6', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.257, 'fiscal_year': '2081'}}, {'text': 'नवप्रवर्तनमा आधारित स्थानीय आर्थिक विकास कार्यक्रम सञ्चालन गर्न रु. ३५ करोड विनियोजन गरेको छु।', 'metadata': {'page': 25, 'sentence_id': 'p25_s7', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.22, 'fiscal_year': '2081'}}, {'text': 'गैरआवासीय नेपालीद्वारा स्थापित एनआरएन डेभैलपमेन्ट फण्डको उपयोग र लगानीका थप अवसर प्रवर्द्धन गर्न सहजीकरण गरिनेछ।', 'metadata': {'page': 25, 'sentence_id': 'p25_s11', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.217, 'fiscal_year': '2081'}}, {'text': 'यस आयोजनाको लागि रु. २ अर्ब ८७ करोड विनियोजन गरेको छु।', 'metadata': {'page': 26, 'sentence_id': 'p26_s3', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.227, 'fiscal_year': '2081'}}, {'text': 'यस आयोजनाको लागि रु. १ अर्ब ६० करोड विनियोजन गरेको छु।', 'metadata': {'page': 26, 'sentence_id': 'p26_s5', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.229, 'fiscal_year': '2081'}}, {'text': 'यस आयोजनाको लागि रु. २ अर्ब विनियोजन गरेको छु।', 'metadata': {'page': 26, 'sentence_id': 'p26_s10', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.241, 'fiscal_year': '2081'}}, {'text': '. आयात हुने वस्तु तथा सेवाको गुणस्तर मापदण्ड निर्धारण गरी लागू गरिनेछ।', 'metadata': {'page': 30, 'sentence_id': 'p30_s4', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'], 'scores': 0.209, 'fiscal_year': '2081'}}, {'text': 'उपभोक्ता अधिकारको संरक्षण र सम्वर्ड्धन गर्न तथा उपभोक्तालाई प्राप्त हकको न्यायिक उपचारका लागि उपभोक्ता अदालत स्थापना गर्न बजेट व्यवस्था गरेको छु।', 'metadata': {'page': 30, 'sentence_id': 'p30_s9', 'language': 'ne', 'source': 'Budget Report 2081', 'topics': ['अर्थतन्त्र'],

For Chunking Strategy lets use the sliding Window.Yesma k hunxa vanda kati number of sentence ligdai janey and we also define a overlap jasma 1st chunking ko last sentence 2nd chunking ko first sentence hunxa yesley context ko semantic preserve garxa.

In [94]:
def create_topic_chunks(topic_map, chunk_size=3, overlap=1):
    all_chunks = []
    step = chunk_size - overlap

    for topic, sentences in topic_map.items():

        for i in range(0, len(sentences), step):

            chunk_items = sentences[i:i + chunk_size]

            chunk_text = " ".join([x["text"] for x in chunk_items])

            all_chunks.append({
                "text": chunk_text,
                "metadata": {
                    "topic": topic,
                    "page_numbers": list(set([x["metadata"]["page"] for x in chunk_items])),
                    "sentence_ids": [x["metadata"]["sentence_id"] for x in chunk_items],
                    "source": "Budget Report 2081"
                }
            })

    return all_chunks

In [95]:
Chunks = create_topic_chunks(topic_map)

In [96]:
Chunks[1]

{'text': 'बजेटलाई आर्थिक तथा सामाजिक क्षेत्रमा देखिएका चुनौती सम्बोधन गर्दै आम नागरिकमा आत्मविश्वास र आशा जगाउने दस्तावेजको रूपमा प्रस्तुत गरेको छु। समृद्ध नेपाल, सुखी नेपालीको राष्ट्रिय आकांक्षा पूरा गर्न र आर्थिक सुधारका कार्यक्रम अगाडि बढाउन आगामी आर्थिक वर्षलाई आर्थिक सुधारको वर्ष घोषणा गरेको छु। लगानीसम्बन्धी आठ कानूनमा एकैपटक गरिएको सुधारले सरकारको लगानीमैत्री वातावरण निर्माण गर्ने प्रतिबद्धताको पुनर्पुष्टि भएको छ।',
 'metadata': {'topic': 'अर्थतन्त्र',
  'page_numbers': [1, 2],
  'sentence_ids': ['p1_s5', 'p1_s6', 'p2_s3'],
  'source': 'Budget Report 2081'}}

In [97]:
Chunks[:5]

[{'text': 'विगतमा शुरू गरिएका आर्थिक सुधारका उपलब्धिलाई संस्थागत गर्दै बदलिँदो विश्व अर्थव्यवस्था र नेपालको वस्तुगत आवश्यकतालाई दृष्टिगत गरी अर्थतन्त्रलाई सबल र उत्थानशील बनाउन आवश्यक ठानेको छु। संविधानको परिकल्पना अनुसार राष्ट्रिय अर्थतन्त्रलाई आत्मनिर्भर, स्वतन्त्र तथा उन्नतिशील बनाउँदै समाजवाद उन्मुख समृद्ध राष्ट्र निर्माणका लागि नयाँ चरणको आर्थिक सुधार आवश्यक देखिएको छ । बजेटलाई आर्थिक तथा सामाजिक क्षेत्रमा देखिएका चुनौती सम्बोधन गर्दै आम नागरिकमा आत्मविश्वास र आशा जगाउने दस्तावेजको रूपमा प्रस्तुत गरेको छु।',
  'metadata': {'topic': 'अर्थतन्त्र',
   'page_numbers': [1],
   'sentence_ids': ['p1_s3', 'p1_s4', 'p1_s5'],
   'source': 'Budget Report 2081'}},
 {'text': 'बजेटलाई आर्थिक तथा सामाजिक क्षेत्रमा देखिएका चुनौती सम्बोधन गर्दै आम नागरिकमा आत्मविश्वास र आशा जगाउने दस्तावेजको रूपमा प्रस्तुत गरेको छु। समृद्ध नेपाल, सुखी नेपालीको राष्ट्रिय आकांक्षा पूरा गर्न र आर्थिक सुधारका कार्यक्रम अगाडि बढाउन आगामी आर्थिक वर्षलाई आर्थिक सुधारको वर्ष घोषणा गरेको छु। लगानीसम्बन्धी आठ कानूनमा एकैपटक गरिएको सुधारले सरकारको लगानीमैत्री वातावरण निर्माण गर्ने प्रतिबद्धताको पुनर्पुष्टि भएको छ।',
  'metadata': {'topic': 'अर्थतन्त्र',
   'page_numbers': [1, 2],
   'sentence_ids': ['p1_s5', 'p1_s6', 'p2_s3'],
   'source': 'Budget Report 2081'}},
 {'text': 'लगानीसम्बन्धी आठ कानूनमा एकैपटक गरिएको सुधारले सरकारको लगानीमैत्री वातावरण निर्माण गर्ने प्रतिबद्धताको पुनर्पुष्टि भएको छ। नागरिकको जीवनमा अनुभूतयोग्य परिवर्तन हासिल गर्ने योजनाको उद्देश्य पूरा गर्न सघाउ पुग्ने गरी बजेट तर्जुमा गरेको छु। ७. बजेट तर्जुमा गर्दा नेपालको संविधान, पन्ध्रां योजनाको समीक्षा, सोह्रौं योजनाको सोँच, गणतन्त्रका डेढ दशकको उपलब्धिको सर्मीक्षा, सम्मानित सदनमा पेश गरिएको विनियोजन विधेयकका सिद्धान्त र प्राथमिकता तथा त्यसमाथि माननीय सदस्यहरूबाट प्राप्त सुझाव एवं नेपाल सरकारको नीति तथा कार्यक्रमलाई प्रमुख आधार बनाएको छु।',
  'metadata': {'topic': 'अर्थतन्त्र',
   'page_numbers': [2],
   'sentence_ids': ['p2_s3', 'p2_s5', 'p2_s6'],
   'source': 'Budget Report 2081'}},
 {'text': '७. बजेट तर्जुमा गर्दा नेपालको संविधान, पन्ध्रां योजनाको समीक्षा, सोह्रौं योजनाको सोँच, गणतन्त्रका डेढ दशकको उपलब्धिको सर्मीक्षा, सम्मानित सदनमा पेश गरिएको विनियोजन विधेयकका सिद्धान्त र प्राथमिकता तथा त्यसमाथि माननीय सदस्यहरूबाट प्राप्त सुझाव एवं नेपाल सरकारको नीति तथा कार्यक्रमलाई प्रमुख आधार बनाएको छु। १०. ११. आर्थिक वर्ष २०६४/६५ मा रु खर्ब १५ अर्ब रहेको कुल गार्हस्थ्य उत्पादन चालु आर्थिक वर्ष रु. ५७ खर्ब ५ अर्ब हुने अनुमान छ। प्रति व्यक्ति राष्ट्रिय आय अमेरिकी डलर ४ सय ९१ बाट बढेर १ हजार ४ सय ५६ पुगेको छ।',
  'metadata': {'topic': 'अर्थतन्त्र',
   'page_numbers': [2, 3],
   'sentence_ids': ['p2_s6', 'p3_s1', 'p3_s2'],
   'source': 'Budget Report 2081'}},
 {'text': 'प्रति व्यक्ति राष्ट्रिय आय अमेरिकी डलर ४ सय ९१ बाट बढेर १ हजार ४ सय ५६ पुगेको छ। गुणस्तरीय पूर्वाधारको कमी, दक्ष जनशक्तिको न्यूनता तथा उत्पादन, उत्पादकत्व र रोजगारीमा अपेक्षित वृद्धि हुन नसकेका कारण आर्थिक वृद्धिको दर न्यून हुनपुग्यो। १५. १६. १७. १८. अर्थतन्त्रमा लामो समयदेखि संरचनात्मक चुनौती रहेकोमा पछिल्लो समय सार्वजनिक र निजी लगानी खुम्चिएको, सार्वजनिक वित्तमा असन्तुलन बढ्दै गएको, सार्वजनिक क्रण व्यवस्थापन खर्च बढ्दै गएको र पुँजीगत खर्च गर्ने क्षमता घट्दै गएको कारण थप चुनौती सिर्जना भएको छ।',
  'metadata': {'topic': 'अर्थतन्त्र',
   'page_numbers': [3, 4, 5],
   'sentence_ids': ['p3_s2', 'p4_s11', 'p5_s1'],
   'source': 'Budget Report 2081'}}]

In [98]:
print(len(Chunks))

162

In [99]:
print(len(text_data))

110

In [100]:
import pandas as pd
df = pd.DataFrame(Chunks)

In [101]:
df.head(10)

,text,metadata
0,विगतमा शुरू गरिएका आर्थिक सुधारका उपलब्धिलाई स...,"{'topic': 'अर्थतन्त्र', 'page_numbers': [1], '..."
1,बजेटलाई आर्थिक तथा सामाजिक क्षेत्रमा देखिएका च...,"{'topic': 'अर्थतन्त्र', 'page_numbers': [1, 2]..."
2,लगानीसम्बन्धी आठ कानूनमा एकैपटक गरिएको सुधारले...,"{'topic': 'अर्थतन्त्र', 'page_numbers': [2], '..."
3,"७. बजेट तर्जुमा गर्दा नेपालको संविधान, पन्ध्रा...","{'topic': 'अर्थतन्त्र', 'page_numbers': [2, 3]..."
4,प्रति व्यक्ति राष्ट्रिय आय अमेरिकी डलर ४ सय ९१...,"{'topic': 'अर्थतन्त्र', 'page_numbers': [3, 4,..."
5,१५. १६. १७. १८. अर्थतन्त्रमा लामो समयदेखि संरच...,"{'topic': 'अर्थतन्त्र', 'page_numbers': [5], '..."
6,"सूचना प्रविधिमा आएको क्रान्ति, कृत्रिम बौद्धिक...","{'topic': 'अर्थतन्त्र', 'page_numbers': [5, 6]..."
7,"११. ७) ७) उपभोक्ता मागमा कमी आउनु, कर्जाको विस...","{'topic': 'अर्थतन्त्र', 'page_numbers': [6], '..."
8,चालु आर्थिक वर्षको चैत मसान्तसम्म आयात २ प्रति...,"{'topic': 'अर्थतन्त्र', 'page_numbers': [6], '..."
9,विदेशी मुद्राको सञ्चिति १२ महिनाको वस्तु र सेव...,"{'topic': 'अर्थतन्त्र', 'page_numbers': [6], '..."

In [102]:
df.head(10)

,text,metadata
0,विगतमा शुरू गरिएका आर्थिक सुधारका उपलब्धिलाई स...,"{'topic': 'अर्थतन्त्र', 'page_numbers': [1], '..."
1,बजेटलाई आर्थिक तथा सामाजिक क्षेत्रमा देखिएका च...,"{'topic': 'अर्थतन्त्र', 'page_numbers': [1, 2]..."
2,लगानीसम्बन्धी आठ कानूनमा एकैपटक गरिएको सुधारले...,"{'topic': 'अर्थतन्त्र', 'page_numbers': [2], '..."
3,"७. बजेट तर्जुमा गर्दा नेपालको संविधान, पन्ध्रा...","{'topic': 'अर्थतन्त्र', 'page_numbers': [2, 3]..."
4,प्रति व्यक्ति राष्ट्रिय आय अमेरिकी डलर ४ सय ९१...,"{'topic': 'अर्थतन्त्र', 'page_numbers': [3, 4,..."
5,१५. १६. १७. १८. अर्थतन्त्रमा लामो समयदेखि संरच...,"{'topic': 'अर्थतन्त्र', 'page_numbers': [5], '..."
6,"सूचना प्रविधिमा आएको क्रान्ति, कृत्रिम बौद्धिक...","{'topic': 'अर्थतन्त्र', 'page_numbers': [5, 6]..."
7,"११. ७) ७) उपभोक्ता मागमा कमी आउनु, कर्जाको विस...","{'topic': 'अर्थतन्त्र', 'page_numbers': [6], '..."
8,चालु आर्थिक वर्षको चैत मसान्तसम्म आयात २ प्रति...,"{'topic': 'अर्थतन्त्र', 'page_numbers': [6], '..."
9,विदेशी मुद्राको सञ्चिति १२ महिनाको वस्तु र सेव...,"{'topic': 'अर्थतन्त्र', 'page_numbers': [6], '..."

Now lets filter the chunks like if chunks has no words and chunk length less than 30.

In [103]:
# filtered_chunks = [chunk for chunk in Chunks 
#                     if chunk["Chunk_Text"] #if chunks has text
#                   and  chunk["Chunk_Text"].strip() != ""  #if chunks is not empty
#                   and len(chunk["Chunk_Text"]) > 30
#                     ]


filtered_chunks = [
    chunk for chunk in Chunks
    if chunk.get("text")
    and chunk["text"].strip()
    and len(chunk["text"].split()) >= 5  #chunks has atleast 5 word
    and chunk.get("metadata") is not None   #must have atleast 1 sentence
]

In [104]:
print(len(filtered_chunks))

162

In [105]:
filtered_chunks[1]

{'text': 'बजेटलाई आर्थिक तथा सामाजिक क्षेत्रमा देखिएका चुनौती सम्बोधन गर्दै आम नागरिकमा आत्मविश्वास र आशा जगाउने दस्तावेजको रूपमा प्रस्तुत गरेको छु। समृद्ध नेपाल, सुखी नेपालीको राष्ट्रिय आकांक्षा पूरा गर्न र आर्थिक सुधारका कार्यक्रम अगाडि बढाउन आगामी आर्थिक वर्षलाई आर्थिक सुधारको वर्ष घोषणा गरेको छु। लगानीसम्बन्धी आठ कानूनमा एकैपटक गरिएको सुधारले सरकारको लगानीमैत्री वातावरण निर्माण गर्ने प्रतिबद्धताको पुनर्पुष्टि भएको छ।',
 'metadata': {'topic': 'अर्थतन्त्र',
  'page_numbers': [1, 2],
  'sentence_ids': ['p1_s5', 'p1_s6', 'p2_s3'],
  'source': 'Budget Report 2081'}}

In [106]:
print(len(Chunks))
print(len(filtered_chunks))

162
162

now we gonna use the Sentence Transformer from Hugging face 'paraphrase-multilingual-MiniLM-L12-v2'  for Embeddings

In [107]:
#Now Embeddings

for chunk in filtered_chunks:
    chunk["Chunk_Embedding"] = model.encode(chunk["text"]).tolist()

In [108]:
filtered_chunks[1]

{'text': 'बजेटलाई आर्थिक तथा सामाजिक क्षेत्रमा देखिएका चुनौती सम्बोधन गर्दै आम नागरिकमा आत्मविश्वास र आशा जगाउने दस्तावेजको रूपमा प्रस्तुत गरेको छु। समृद्ध नेपाल, सुखी नेपालीको राष्ट्रिय आकांक्षा पूरा गर्न र आर्थिक सुधारका कार्यक्रम अगाडि बढाउन आगामी आर्थिक वर्षलाई आर्थिक सुधारको वर्ष घोषणा गरेको छु। लगानीसम्बन्धी आठ कानूनमा एकैपटक गरिएको सुधारले सरकारको लगानीमैत्री वातावरण निर्माण गर्ने प्रतिबद्धताको पुनर्पुष्टि भएको छ।',
 'metadata': {'topic': 'अर्थतन्त्र',
  'page_numbers': [1, 2],
  'sentence_ids': ['p1_s5', 'p1_s6', 'p2_s3'],
  'source': 'Budget Report 2081'},
 'Chunk_Embedding': [-0.05050157010555267,
  0.1752856969833374,
  -0.12584248185157776,
  -0.05113665759563446,
  0.1394929736852646,
  0.1984349638223648,
  -0.1536068618297577,
  -0.032505910843610764,
  -0.06978660821914673,
  0.17863966524600983,
  0.043943896889686584,
  0.16981181502342224,
  0.0462067686021328,
  -0.027587583288550377,
  0.10098961740732193,
  0.017281608656048775,
  -0.0539277121424675,
  0.022853480651974678,
  -0.03306730091571808,
  0.22743621468544006,
  0.06836987286806107,
  -0.019647307693958282,
  -0.011694235727190971,
  -0.00953605119138956,
  0.13244830071926117,
  -0.0409860759973526,
  0.029118450358510017,
  -0.11852632462978363,
  0.019553223624825478,
  -0.08380717039108276,
  0.06118609011173248,
  -0.04438088834285736,
  0.046135805547237396,
  0.061202071607112885,
  0.07996397465467453,
  0.03475894033908844,
  0.19917505979537964,
  0.016580695286393166,
  0.03820311278104782,
  0.09769972413778305,
  -0.08260397613048553,
  -0.11815982311964035,
  -0.011736005544662476,
  0.0013602081453427672,
  -0.015878338366746902,
  -0.09610006213188171,
  0.10497521609067917,
  -0.022818222641944885,
  -0.2879505753517151,
  0.025654355064034462,
  -0.015273096971213818,
  -0.0857098326086998,
  -0.09850679337978363,
  -0.04239541292190552,
  0.022699948400259018,
  0.02589244954288006,
  0.06731461733579636,
  0.05313154309988022,
  0.012483401224017143,
  -0.1292087286710739,
  0.021559670567512512,
  0.028767209500074387,
  -0.05585595965385437,
  0.02686333656311035,
  0.09289976954460144,
  0.036750681698322296,
  0.0007093679159879684,
  0.01275639794766903,
  -0.07904355227947235,
  0.09141846001148224,
  0.0004338423314038664,
  0.010728077031672001,
  0.04275932163000107,
  -0.1962636113166809,
  0.03609826788306236,
  -0.08759047091007233,
  0.07920467108488083,
  0.1871681809425354,
  0.10134483128786087,
  -0.10991553962230682,
  0.10628128051757812,
  0.1640329211950302,
  -0.036972638219594955,
  -0.015514017082750797,
  -0.1770937591791153,
  -0.07973539084196091,
  0.06653759628534317,
  0.07958270609378815,
  0.11079870164394379,
  -0.2418135702610016,
  0.008794989436864853,
  0.17735056579113007,
  0.32318177819252014,
  -0.06574159115552902,
  0.033570677042007446,
  0.05082419887185097,
  0.006022158078849316,
  -0.08760872483253479,
  0.00993783213198185,
  -0.04915710538625717,
  -0.12530289590358734,
  0.12089559435844421,
  -0.10565277934074402,
  -0.18724147975444794,
  0.027897590771317482,
  -0.01573002152144909,
  -0.09039684385061264,
  -0.15349890291690826,
  0.028102217242121696,
  0.03222838044166565,
  0.013363590463995934,
  0.009279459714889526,
  -0.06841643154621124,
  -0.03715921938419342,
  0.03084898181259632,
  -0.011492769233882427,
  -0.04752900078892708,
  0.005913293454796076,
  0.05623456835746765,
  -0.002917639911174774,
  -0.013631140813231468,
  -0.07907567173242569,
  -0.01637069322168827,
  -0.17054785788059235,
  0.11039238423109055,
  0.015999728813767433,
  0.01062709465622902,
  -0.07928266376256943,
  0.057174693793058395,
  -0.069279745221138,
  -0.0600019209086895,
  -0.07136305421590805,
  -0.05701649188995361,
  -0.025316789746284485,
  0.07876086980104446,
  -0.1177024096250534,
  -0.0057314480654895306,
  0.04136977344751358,
  0.07074878364801407,
  0.10077511519193649,
  0.1783759593963623,
  0.23940765857696533,
  0.038143910467624664,
  0.07791407406330109,
  -0.13573923707008362,
  0.10933209210634232,
  0.17054972052574158,
  0.05347118526697159,
  0.15457181632518768,
  0.02417823113501072,
  0.2184799462556839,
  -0.08212237805128098,
  0.1570834368467331,
  -0.05951089411973953,
  0.031007086858153343,
  0.06536488980054855,
  -0.001574491267092526,
  0.02335609495639801,
  0.11974478513002396,
  0.16006658971309662,
  -0.11341966688632965,
  0.03561188653111458,
  -0.10686550289392471,
  -0.03935803100466728,
  -0.003500694176182151,
  -0.12804965674877167,
  -0.07063945382833481,
  -0.2065345048904419,
  0.14536485075950623,
  0.03541099652647972,
  0.13667064905166626,
  -0.026274297386407852,
  0.08401968330144882,
  0.04631248116493225,
  0.18130812048912048,
  -0.07457388192415237,
  -0.0824943482875824,
  -0.031845804303884506,
  -0.07415995746850967,
  0.04858056455850601,
  0.1166294664144516,
  -0.20822563767433167,
  0.015623570419847965,
  -0.2301727831363678,
  -0.1377512663602829,
  -0.02705041505396366,
  -0.0831073597073555,
  -0.12109538167715073,
  -0.10993482917547226,
  -0.09786655008792877,
  -0.0731261596083641,
  0.010066883638501167,
  0.008033602498471737,
  0.29669126868247986,
  -0.15312719345092773,
  -0.11531752347946167,
  0.020155081525444984,
  -0.028327953070402145,
  0.013910377398133278,
  -0.027804533019661903,
  -0.3522166907787323,
  -0.014061124995350838,
  -0.11758797615766525,
  0.002534890314564109,
  0.07182686775922775,
  -0.11396458745002747,
  0.18027719855308533,
  -0.19509249925613403,
  0.06915955990552902,
  -0.12197341024875641,
  0.15977200865745544,
  0.07713567465543747,
  0.09406966716051102,
  -0.04225114732980728,
  0.014810276217758656,
  0.043457578867673874,
  0.12194059044122696,
  0.05079225078225136,
  -0.2213924378156662,
  -0.053544964641332626,
  0.027609288692474365,
  0.031068861484527588,
  0.095674067735672,
  -0.15467700362205505,
  -0.24221257865428925,
  -0.016281161457300186,
  -0.2087554931640625,
  0.1263781636953354,
  0.1476244479417801,
  0.07252603024244308,
  -0.14661620557308197,
  -0.30669087171554565,
  0.11992143094539642,
  0.03208830952644348,
  -0.2028903067111969,
  -0.2179032862186432,
  0.25034233927726746,
  0.15188921988010406,
  -0.1699654757976532,
  -0.05046644061803818,
  -0.07896067202091217,
  -0.1545494943857193,
  0.04609471932053566,
  -0.1367383599281311,
  0.04585157707333565,
  0.06098317727446556,
  -0.11058520525693893,
  0.11935143172740936,
  -0.020666582509875298,
  0.0031798796262592077,
  -0.03498948737978935,
  -0.4131462275981903,
  0.1425561010837555,
  -0.0888957530260086,
  -0.08293271064758301,
  -0.10132557153701782,
  -0.20560312271118164,
  -0.03480706736445427,
  0.008013077080249786,
  0.06169509515166283,
  -0.012991524301469326,
  -0.11150248348712921,
  -0.14046940207481384,
  0.3236059546470642,
  0.14066876471042633,
  -0.13800252974033356,
  -0.04453613609075546,
  0.03499922156333923,
  0.019151397049427032,
  0.1255774050951004,
  0.0022060994524508715,
  -0.04958079755306244,
  0.05622291564941406,
  0.03835560381412506,
  0.09993395209312439,
  0.028983833268284798,
  0.04226626455783844,
  -0.03772781789302826,
  0.06101008132100105,
  0.160472109913826,
  0.07427433878183365,
  0.02585877850651741,
  0.09493681788444519,
  0.020297637209296227,
  -0.11339710652828217,
  0.06299610435962677,
  0.09824254363775253,
  -0.10860948264598846,
  0.023443112149834633,
  0.044995274394750595,
  -0.06527861952781677,
  -0.031957466155290604,
  0.18865375220775604,
  0.0026153901126235723,
  -0.022356066852808,
  -0.1631876528263092,
  -0.13284550607204437,
  0.04063917323946953,
  0.12358223646879196,
  0.09298429638147354,
  0.11162502318620682,
  -0.04009433835744858,
  -0.011769686825573444,
  0.05951887369155884,
  0.049777112901210785,
  0.034002650529146194,
  0.16680479049682617,
  0.022135665640234947,
  0.03363008052110672,
  -0.0766744464635849,
  0.10898720473051071,
  -0.2075154036283493,
  0.025009339675307274,
  0.27737993001937866,
  -0.03782130777835846,
  -0.00873536616563797,
  -0.0014110367046669126,
  0.01715966872870922,
  0.09629536420106888,
  -0.16523593664169312,
  0.2443164587020874,
  0.06290068477392197,
  -0.11852604150772095,
  0.09640270471572876,
  -0.009896772913634777,
  0.02913637086749077,
  0.030764063820242882,
  -0.09396878629922867,
  -0.020667679607868195,
  -0.09495947510004044,
  0.1298546940088272,
  0.1013098657131195,
  0.04713054746389389,
  -0.030267726629972458,
  -0.1646244376897812,
  0.09135311841964722,
  -0.08732079714536667,
  0.0949544608592987,
  -0.12091407924890518,
  0.033987872302532196,
  0.1816304624080658,
  0.11552473902702332,
  -0.14775602519512177,
  -0.0906013622879982,
  0.0017776157474145293,
  -0.06626341491937637,
  -0.015182082541286945,
  0.13661792874336243,
  -0.12886708974838257,
  0.015733884647488594,
  -0.054001111537218094,
  -0.04886341094970703,
  -0.08127307891845703,
  -0.17413319647312164,
  -0.01696600392460823,
  -0.0071326969191432,
  -0.03595023974776268,
  0.07597475498914719,
  0.049178242683410645,
  -0.17963190376758575,
  0.02872665785253048,
  0.18165075778961182,
  0.00565022649243474,
  0.16757570207118988,
  -0.008068103343248367,
  -0.09384578466415405,
  -0.14734908938407898,
  -0.08366701751947403,
  0.11579322069883347,
  -0.08578226715326309,
  -0.011743435636162758,
  -0.11426106840372086,
  0.04027066379785538,
  0.03061768040060997,
  0.18084047734737396,
  0.11943914741277695,
  -0.0371929295361042,
  0.14590227603912354,
  -0.1597655564546585,
  -0.07591436803340912,
  0.06301488727331161,
  0.004707937128841877,
  0.057039182633161545,
  0.13008667528629303]}

Now take the text chunks only and store then do embeddings

Now lets Install FAISS Vector Database.It uses a ANN for the nearest neighbor search and retrieve the relevant text.

In [59]:
import faiss 
import numpy as np

#lets suppose docs 
docs = [
     "काठमाडौं नेपालको राजधानी हो",
    "एभरेस्ट संसारको सबैभन्दा अग्लो हिमाल हो",
    "नेपालमा धेरै धार्मिक स्थलहरू छन्",
    "पशुपतिनाथ मन्दिर काठमाडौंमा छ",
]

#convert the docs to embeddings 
embedding = model.encode(docs).astype('float32') #usually numpy array 64 bit hunxa so faiss ley 32 bit ma matra kaam garxa
d = embedding.shape[1]

#create vector db in indices and vector
index = faiss.IndexFlatL2(d)
index.add(embedding)

query = "नेपालको सबैभन्दा अग्लो हिमाल कुन हो?"
query_vector = model.encode([query]).astype('float32')

distance,indices = index.search(query_vector,k=2)

print("Best chunks:")
for indice in indices[0]:
    print(f"{docs[indice]}")

Best chunks:
एभरेस्ट संसारको सबैभन्दा अग्लो हिमाल हो
काठमाडौं नेपालको राजधानी हो

In [60]:
#use for good text 
import textwrap
def print_wrapped(text,wrap_length=80):
  wrapped_text = textwrap.fill(text,wrap_length)
  print(wrapped_text)

Now lets use our Embeddings to retrieve the chunk

The retrieve chunks are unrelevant so lets use and see Hybrid search for better keyword matching i.e BM25

Lets Use Topic wise Retrieval using the metadata and topic in filtered_text ,So

In [69]:
#At first User Query is 
user_query = "नेपालमा हाल शिक्षा क्षेत्रमा भएका मुख्य सुधारहरू के के हुन्?"

In [109]:
#At first lets make Topic map for token 
#सबै sentences लाई उनीहरूको topic अनुसार छुट्याएर groups बनाउँछ
from collections import defaultdict

def group_by_topic(data):
    topic_map = defaultdict(list)

    for item in data:
        topics = item["metadata"].get("topics",[])

        #if there are no topics
        if len(topics) == 0:
            topic = "other"
        else:
            topic = topics[0]  #Primary topics

        topic_map[topic].append(item)

    return topic_map

In [110]:
topic_map = group_by_topic(filtered_chunks)

In [111]:
def detect_topic(user_query,topic_map):
    user_query = user_query.lower()

    for topic in topic_map.keys():
        if topic.lower() in user_query:
            return topic

    return "other"

Now keyword Matching Using BM25

In [112]:
from rank_bm25 import BM25Okapi
import numpy as np

def build_bm25(docs):

    tokenized_doc = [item["text"].split() for item in docs]
    bm25 = BM25Okapi(tokenized_doc)

    return bm25

Now Build for FAISS index

In [113]:
import faiss
import numpy as np
def build_faiss(docs):
    embeddings = np.array([doc["Chunk_Embedding"] for doc in docs]).astype("float32")

    index = faiss.IndexFlatL2(embeddings.shape[1])

    #add embedding to index
    index.add(embeddings)

    return index

In [114]:
#Now hybrid Search bm25 + Faiss
def hybrid_search(user_query,topic_map,model,top_k=5,alpha=0.5):
    #detect topic
    topic = detect_topic(user_query,topic_map)
    
    #gets the document of that topic (tyo topic ko sabai documents ligxa)
    docs = topic_map.get(topic,[])

    if len(docs) == 0:
        return []

    #BM25 search
    bm25 = build_bm25(docs)
    tokenized_query = user_query.split()
    bm25_score = bm25.get_scores(tokenized_query)

    #Normalize Bm25 scores(0 to 1)
    bm25_scores = np.array(bm25_score)
    bm25_scores = bm25_scores / (bm25_scores.max() + 1e-8)


    #Faisss Search
    index = build_faiss(docs)

    user_query_vector = model.encode([user_query]).astype("float32")
    
    distance,indices = index.search(user_query_vector,len(docs))

    #convert distance to similarity
    faiss_scores = 1/(1+distance[0])

    #normalize FAISS scores
    faiss_scores = faiss_scores/(faiss_scores.max()+1e-8)

    #combine Scores 
    hybrid_scores = alpha * bm25_scores + (1-alpha)*faiss_scores
    #Rank top Results
    top_indices = np.argsort(hybrid_scores)[::-1][:top_k]
    results = [docs[i] for i in top_indices]

    return results

In [119]:
user_query = "आगामी आर्थिक वर्षको लागि अनुमान गरिएको कुल सरकारी खर्च (बजेटको कुल आकार) कति हो र त्यसमध्ये चालु खर्चको हिस्सा कति प्रतिशत छ?"

In [120]:
results = hybrid_search(user_query,topic_map,model)

In [121]:
for item in results:
    print("Text:",item["text"])
    print("TOPIC:",item["metadata"]["topic"])
    print("*"*50)

Text: कुल सरकारी खर्च मध्ये चालु खर्च रु. १० खर्ब ६७ अर्ब ४९ करोड अर्थात विनियोजनको ९३ प्रतिशत, पुँजीगत खर्च रु. २ खर्ब १५ अर्ब ३० करोड अर्थात विनियोजनको ७१ प्रतिशत र बित्तीय व्यवस्थातर्फ रु. २ खर्ब ४७ अर्ब ५५ करोड अर्थात विनियोजनको ८० प्रतिशत खर्च हुने संशोधित अनुमान छ। चालु आर्थिक वर्ष राजस्व संकलन रु. १२ खर्ब ५३ अर्ब ५२ करोड संशोधित हुने अनुमान छ यो लक्ष्यको तुलनामा ८८ प्रतिशत हो। चालु आर्थिक वर्षको लागि खर्च व्यहोर्ने स्रोतमध्ये आन्तरिक क्रणबाट रु. २ खर्ब ४० अर्ब व्यहोरिने अनुमान रहेकोमा वैशाख मसान्तसम्म रु. १ खर्ब ९१ अर्ब उठाइएको छ।
TOPIC: अर्थतन्त्र
**************************************************
Text: विदेशी मुद्राको सञ्चिति १२ महिनाको वस्तु र सेवा आयात धान्न पर्याप्त रहेको छ। आर्थिक वर्ष २०८०%८१ मा कुल सरकारी खर्च रु. १५ खर्ब ३० अर्ब ३५ करोड अर्थात विनियोजनको ८७ प्रतिशत हुने संशोधित अनुमान छ। कुल सरकारी खर्च मध्ये चालु खर्च रु. १० खर्ब ६७ अर्ब ४९ करोड अर्थात विनियोजनको ९३ प्रतिशत, पुँजीगत खर्च रु. २ खर्ब १५ अर्ब ३० करोड अर्थात विनियोजनको ७१ प्रतिशत र बित्तीय व्यवस्थातर्फ रु. २ खर्ब ४७ अर्ब ५५ करोड अर्थात विनियोजनको ८० प्रतिशत खर्च हुने संशोधित अनुमान छ।
TOPIC: अर्थतन्त्र
**************************************************
Text: ३०३. आगामी आर्थिक वर्षका लागि कुल खर्च रु. १८ खर्ब ६० अर्ब ३० करोड विनियोजन गरेको छु। कुल विनियोजनमध्ये चालुतर्फ रु. ११ खर्ब ४० अर्ब ६६ करोड अर्थात्‌ ६१ प्रतिशत, पुँजीगततर्फ रु. ३ खर्ब ५२ अर्ब ३५ करोड अर्थात्‌ १८ प्रतिशत र वित्तीय व्यवस्थातर्फ रु. ३ खर्ब ६७ अर्ब २८ करोड अर्थात्‌ १९ प्रतिशत रहेको छ। यो खर्च अनुमान चालु आर्थिक वर्षको विनियोजनको तुलनामा ६ प्रतिशतले बढी र संशोधित अनुमानको तुलनामा २१ प्रतिशतले बढी हो।
TOPIC: अर्थतन्त्र
**************************************************
Text: यो खर्च अनुमान चालु आर्थिक वर्षको विनियोजनको तुलनामा ६ प्रतिशतले बढी र संशोधित अनुमानको तुलनामा २१ प्रतिशतले बढी हो। कुल विनियोजनमा प्रदेश र स्थानीय तहमा वित्तीय हस्तान्तरण तर्फ रु. ४ खर्ब ८ अर्ब ८७ करोड विनियोजन रहेको छ। ३०४. आगामी आर्थिक वर्षका लागि अनुमान गरिएको खर्च व्यहोर्ने स्रोत मध्ये राजस्वबाट रु. १२ खर्ब ६० अर्ब ३० करोड र वैदेशिक अनुदानबाट रु. ५२ अर्ब इइ करोड व्यहोर्दा रु. ५ खर्ब ४७ अर्ब ६७ करोड न्यून हुनेछ।
TOPIC: अर्थतन्त्र
**************************************************
Text: चालु आर्थिक वर्षको लागि खर्च व्यहोर्ने स्रोतमध्ये आन्तरिक क्रणबाट रु. २ खर्ब ४० अर्ब व्यहोरिने अनुमान रहेकोमा वैशाख मसान्तसम्म रु. १ खर्ब ९१ अर्ब उठाइएको छ। २४. चालु आर्थिक वर्षको मन्त्रालय र निकायगत बजेट विनियोजन र खर्चको प्रगति विवरण, मुलुकको प्रमुख आर्थिक-सामाजिक परिसूचक र तथ्याङ्क समावेश भएको आर्थिक सर्वेक्षण र सार्वजनिक संस्थानको प्रगति समेटिएको विवरण सम्मानित सदन समक्ष पेश गरिसकेको छु। बजेटका पाँच उद्देश्य देहायबमोजिम रहेका छन्‌ः (1) उत्पादन, उत्पादकत्व र रोजगारी वृद्धि गर्नु, (2) निजी क्षेत्रको मनोबल बढाउँदै लगानी वृद्धि गर्नु र आर्थिक क्रियाकलापमा तीव्रता ल्याउनु, (३) मानव संसाधन विकास गर्नु, (4) स्रोत र साधनलाई सन्तुलित र समन्यायिक ढङ्गले परिचालन गरी आर्थिक असमानता र गरिबी न्यूनीकरण गर्नु, र (5) सार्वजनिक सेवा प्रवाहलाई प्रभावकारी बनाउनु ।
TOPIC: अर्थतन्त्र
**************************************************

In [118]:
from collections import Counter

def count_topics(data):
    topics = []

    for chunk in data:
        topic = chunk["metadata"].get("topic", "other")
        topics.append(topic)

    return Counter(topics)


counts = count_topics(filtered_chunks)

print(counts)

Counter({'अर्थतन्त्र': 72, 'पूर्वाधार': 18, 'शिक्षा': 15, 'कृषि': 14, 'विज्ञान तथा प्रविधि': 14, 'स्वास्थ्य': 12, 'उद्योग र व्यापार': 7, 'सामाजिक सुरक्षा': 6, 'पर्यटन': 4})

NOW Use the llama3.2 llm using ollama

In [129]:
!pip install langchain-community -q

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [140]:
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage, AIMessage
from langchain_core.runnables import RunnableLambda

# 1. LLM
llm = ChatOllama(
    model="llama3.2",
    num_ctx=8192
)

# 2. Manual memory (simple list)
chat_history = []

# 3. Chat function
def chat(input_text):
    global chat_history

    # Add user message
    chat_history.append(HumanMessage(content=input_text))

    # Send full history to LLM
    response = llm.invoke(chat_history)

    # Save AI response
    chat_history.append(AIMessage(content=response.content))

    return response.content


# 4. Run loop
while True:
    user_input = input("You: ")
    if user_input.lower() in ["exit", "quit"]:
        break

    answer = chat(user_input)
    print("AI:", answer)

ModuleNotFoundError: No module named 'langchain_core.tracers.context'